"""Persistence + apply for grouping plans over the live requirement store.

A grouping plan is generated by ``build_grouping_plan`` (dedup, read-only) and
persisted here as ``GroupingPlan`` + ``GroupingGroup`` rows, so the agent
(``/agrupar``) and the requirements UI curate the SAME data. ``apply_plan``
merges the groups whose ``decision`` is ``accept`` via ``merge_requirements``.

Replaces the previous Markdown-file store: the plan is now a DB row, and the
Markdown is a read-only export (``export_plan_md`` → ``serialize_plan_md``).

Idempotency: ``apply_plan`` re-validates every group against the live store on
each call, so a group whose members are already ``MERGED`` into the keeper is
reported ``already_applied`` and skipped — never re-merged (``merge_requirements``
appends revisions, so a blind re-apply would duplicate the audit trail). The
``decision`` per group + ``status`` per plan are the shared guard so the agent
and the UI never double-apply.
"""
from __future__ import annotations

import logging
from datetime import datetime

from sqlalchemy import delete, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.agents.pipelines.grouping import (
    Group,
    GroupingPlan as GroupingPlanData,
    serialize_plan_md,
)
from backend.models.requirement import (
    GroupDecision,
    GroupingGroup,
    GroupingPlan,
    PlanStatus,
    RequirementItem,
    ReqStatus,
)
from backend.services import requirement_store as store

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Persist (GroupingPlan dataclass → DB rows)
# ---------------------------------------------------------------------------

async def persist_plan(
    session: AsyncSession, plan: GroupingPlanData, project_id: int
) -> int:
    """Persist a GroupingPlan (from ``build_grouping_plan``) as DB rows.

    REQ-codes in the plan are resolved to ``RequirementItem`` ids at persist
    time. Groups whose keeper or any member can't be resolved are dropped
    (logged), so a stale ref never blocks persisting the rest.

    Returns the new plan id.
    """
    items = await store.list_requirements(
        session, project_id, include_deleted=True
    )
    by_code = {it.code: it for it in items}

    row = GroupingPlan(project_id=project_id, status=PlanStatus.PROPOSED)
    session.add(row)
    await session.flush()  # populate row.id

    dropped = 0
    for g in plan.groups:
        keeper = by_code.get(g.keeper_code)
        if keeper is None:
            dropped += 1
            continue
        member_ids: list[int] = []
        ok = True
        for code in g.member_codes:
            m = by_code.get(code)
            if m is None:
                ok = False
                break
            member_ids.append(m.id)
        if not ok or not member_ids:
            dropped += 1
            continue
        session.add(GroupingGroup(
            plan_id=row.id,
            keeper_id=keeper.id,
            member_ids=member_ids,
            reason=g.reason,
            confidence=float(g.confidence or 0.0),
            decision=GroupDecision.PENDING,
        ))
    await session.commit()
    if dropped:
        logger.info(
            "persist_plan: dropped %d group(s) with unresolvable refs", dropped
        )
    return row.id


# ---------------------------------------------------------------------------
# Reads
# ---------------------------------------------------------------------------

async def list_plans(session: AsyncSession, project_id: int) -> list[dict]:
    """Summaries of every plan for a project, newest first."""
    stmt = (
        select(GroupingPlan)
        .where(GroupingPlan.project_id == project_id)
        .order_by(GroupingPlan.generated_at.desc())
    )
    rows = (await session.scalars(stmt)).all()
    out: list[dict] = []
    for r in rows:
        groups = (
            await session.scalars(
                select(GroupingGroup).where(GroupingGroup.plan_id == r.id)
            )
        ).all()
        out.append({
            "id": r.id,
            "status": r.status.value,
            "generated_at": r.generated_at.isoformat() if r.generated_at else None,
            "applied_at": r.applied_at.isoformat() if r.applied_at else None,
            "groups": len(groups),
            "accepted": sum(
                1 for g in groups if g.decision == GroupDecision.ACCEPT
            ),
        })
    return out


async def delete_all_plans(
    session: AsyncSession, project_id: int
) -> int:
    """Hard-delete every grouping plan + its groups for a project.

    Groups first (FK -> grouping_plans), then the plans. Does NOT commit; the
    caller owns the transaction (see ``reset_project_capture`` in
    requirements_service). Returns the count of plans deleted.
    """
    count = await session.scalar(
        select(func.count()).select_from(GroupingPlan).where(
            GroupingPlan.project_id == project_id
        )
    )
    total = int(count or 0)
    if total == 0:
        return 0
    plan_ids = select(GroupingPlan.id).where(
        GroupingPlan.project_id == project_id
    )
    await session.execute(
        delete(GroupingGroup).where(GroupingGroup.plan_id.in_(plan_ids))
    )
    await session.execute(
        delete(GroupingPlan).where(
            GroupingPlan.project_id == project_id
        )
    )
    await session.flush()
    return total


async def get_plan(session: AsyncSession, plan_id: int) -> dict | None:
    """Full plan with groups; keeper/members resolved to codes for display."""
    row = await session.get(GroupingPlan, plan_id)
    if row is None:
        return None
    groups = (
        await session.scalars(
            select(GroupingGroup)
            .where(GroupingGroup.plan_id == plan_id)
            .order_by(GroupingGroup.id)
        )
    ).all()

    ids: set[int] = set()
    for g in groups:
        ids.add(g.keeper_id)
        ids.update(g.member_ids)
    items: dict[int, RequirementItem] = {}
    if ids:
        rows = (
            await session.scalars(
                select(RequirementItem).where(RequirementItem.id.in_(ids))
            )
        ).all()
        items = {it.id: it for it in rows}

    return {
        "id": row.id,
        "project_id": row.project_id,
        "status": row.status.value,
        "generated_at": row.generated_at.isoformat() if row.generated_at else None,
        "applied_at": row.applied_at.isoformat() if row.applied_at else None,
        "groups": [_group_dict(g, items) for g in groups],
    }


def _item_brief(it: RequirementItem | None) -> dict:
    """Campos relevantes para curar UN requerimiento (keeper o miembro).

    El payload del grupo debe bastar para curar sin llamadas extra: los
    criterios de curacion usan statement (especificidad), priority (gana la
    mas restrictiva), explicit_priority (keeper explícito del cliente) y las
    fuentes (desempate por documento). ``get_requirement`` queda para el
    detalle completo de UN item cuando el usuario lo pide.
    """
    if it is None:
        return {
            "id": None, "code": None, "statement": None, "type": None,
            "priority": None, "explicit_priority": None, "status": None,
            "source_documents": [],
        }
    docs: list[str] = []
    for entry in store._source_list(it):
        doc_id = entry.get("document_id") if isinstance(entry, dict) else None
        if isinstance(doc_id, str) and doc_id and doc_id not in docs:
            docs.append(doc_id)
    return {
        "id": it.id,
        "code": it.code,
        "statement": it.statement,
        "type": it.type.value if it.type else None,
        "priority": it.priority.value if it.priority else None,
        "explicit_priority": bool(it.explicit_priority),
        "status": it.status.value if it.status else None,
        "source_documents": docs,
    }


def _group_dict(g: GroupingGroup, items: dict[int, RequirementItem]) -> dict:
    return {
        "id": g.id,
        "keeper": _item_brief(items.get(g.keeper_id)),
        "members": [_item_brief(items.get(mid)) for mid in g.member_ids],
        "reason": g.reason,
        "confidence": g.confidence,
        "decision": g.decision.value,
    }


# ---------------------------------------------------------------------------
# Curation (agent + UI edit the same rows)
# ---------------------------------------------------------------------------

async def set_group_decision(
    session: AsyncSession, group_id: int, decision: GroupDecision
) -> dict | None:
    """Flip a group's curation decision (pending/accept/reject)."""
    g = await session.get(GroupingGroup, group_id)
    if g is None:
        return None
    g.decision = decision
    await session.commit()
    return {"id": g.id, "decision": g.decision.value}


async def update_group(
    session: AsyncSession,
    group_id: int,
    *,
    keeper_id: int | None = None,
    member_ids: list[int] | None = None,
    reason: str | None = None,
) -> dict | None:
    """Edit a group's keeper and/or members (UI curation). Returns None if
    the group doesn't exist. ``member_ids`` replaces the set when provided."""
    g = await session.get(GroupingGroup, group_id)
    if g is None:
        return None
    if keeper_id is not None:
        g.keeper_id = keeper_id
    if member_ids is not None:
        g.member_ids = list(member_ids)
    if reason is not None:
        g.reason = reason
    await session.commit()
    return {"id": g.id, "keeper_id": g.keeper_id, "member_ids": g.member_ids}


# ---------------------------------------------------------------------------
# Archive (close stale plans without applying)
# ---------------------------------------------------------------------------

async def archive_plan(session: AsyncSession, plan_id: int) -> dict | None:
    """Close a plan as ``ARCHIVED`` (stale/noise cleanup; items untouched).

    Para planes ``proposed`` obsoletos (p. ej. codigos ya resueltos por un plan
    posterior aplicado) que de otro modo se acumulan como ruido. Idempotente
    sobre ``ARCHIVED``; los ``applied`` son historial de auditoria y no se
    archivan. Devuelve None si el plan no existe.
    """
    plan = await session.get(GroupingPlan, plan_id)
    if plan is None:
        return None
    if plan.status == PlanStatus.APPLIED:
        return {
            "error": (
                f"plan {plan_id} ya esta aplicado; los planes aplicados son "
                "historial y no se archivan"
            )
        }
    if plan.status == PlanStatus.ARCHIVED:
        return {"id": plan.id, "status": plan.status.value, "already_archived": True}
    plan.status = PlanStatus.ARCHIVED
    await session.commit()
    return {"id": plan.id, "status": plan.status.value}


# ---------------------------------------------------------------------------
# Apply (merge accept groups idempotently)
# ---------------------------------------------------------------------------

async def apply_plan(
    session: AsyncSession, plan_id: int, *, changed_by: str = "agent"
) -> dict:
    """Merge every ``accept`` group in the plan idempotently, then set status.

    Reuses ``merge_requirements`` (union sources, soft-delete losers as
    ``MERGED``). Groups whose members are already ``MERGED`` into the keeper
    are reported ``already_applied`` and skipped. ``reject`` / ``pending``
    groups are skipped without merging.
    """
    plan = await session.get(GroupingPlan, plan_id)
    if plan is None:
        return {"error": f"plan {plan_id} no existe"}

    groups = (
        await session.scalars(
            select(GroupingGroup)
            .where(GroupingGroup.plan_id == plan_id)
            .order_by(GroupingGroup.id)
        )
    ).all()

    results: list[dict] = []
    applied = already = invalid = skipped = 0
    for g in groups:
        if g.decision != GroupDecision.ACCEPT:
            skipped += 1
            continue
        outcome = await _apply_one(session, g, changed_by=changed_by)
        results.append({**outcome, "group_id": g.id, "keeper_id": g.keeper_id})
        s = outcome["status"]
        if s == "applied":
            applied += 1
        elif s == "already_applied":
            already += 1
        else:
            invalid += 1

    if applied > 0 and invalid == 0 and already == 0:
        plan.status = PlanStatus.APPLIED
    elif applied > 0:
        plan.status = PlanStatus.PARTIALLY_APPLIED
    # else: nothing applied — leave status as-is
    if applied > 0:
        plan.applied_at = datetime.now()
    await session.commit()

    return {
        "id": plan_id,
        "status": plan.status.value,
        "applied": applied,
        "already_applied": already,
        "invalid": invalid,
        "skipped": skipped,
        "groups": results,
    }


async def _apply_one(
    session: AsyncSession, g: GroupingGroup, *, changed_by: str
) -> dict:
    """Merge one group idempotently (keeper absorbs live members)."""
    keeper = await session.get(RequirementItem, g.keeper_id)
    if keeper is None:
        return {"status": "invalid", "reason": f"keeper {g.keeper_id} no existe"}
    if keeper.status == ReqStatus.MERGED:
        return {"status": "invalid", "reason": "el keeper ya está MERGED"}

    members: list[RequirementItem] = []
    missing: list[int] = []
    for mid in g.member_ids:
        m = await session.get(RequirementItem, mid)
        if m is None:
            missing.append(mid)
        else:
            members.append(m)
    if missing:
        return {"status": "invalid", "reason": f"miembros no encontrados: {missing}"}

    live = [m for m in members if m.status != ReqStatus.MERGED]
    merged_into_keeper = [
        m for m in members
        if m.status == ReqStatus.MERGED and m.merged_into == keeper.id
    ]
    if not live:
        if members and len(merged_into_keeper) == len(members):
            return {"status": "already_applied"}
        return {
            "status": "invalid",
            "reason": "todos los miembros ya están MERGED pero no en este keeper",
        }

    ids = [keeper.id] + [m.id for m in live]
    try:
        await store.merge_requirements(
            session, ids, keep_id=keeper.id,
            reason="grouping_plan", changed_by=changed_by,
        )
    except Exception as exc:  # noqa: BLE001
        return {"status": "invalid", "reason": f"merge falló: {exc}"}
    return {"status": "applied", "merged_count": len(live)}


# ---------------------------------------------------------------------------
# Markdown export (read-only view of a persisted plan)
# ---------------------------------------------------------------------------

async def export_plan_md(session: AsyncSession, plan_id: int) -> str | None:
    """Serialize a persisted plan to Markdown (read-only export for audit)."""
    data = await get_plan(session, plan_id)
    if data is None:
        return None
    plan = GroupingPlanData(
        groups=[
            Group(
                keeper_code=g["keeper"]["code"] or "",
                member_codes=[m["code"] for m in g["members"] if m["code"]],
                reason=g["reason"],
                confidence=g["confidence"],
            )
            for g in data["groups"]
        ],
        generated_at=data["generated_at"] or "",
        project=str(data["project_id"]),
        status=data["status"],
    )
    return serialize_plan_md(plan)
