"""MER pipeline: domain entity model extraction from functional requirements.

Multi-pass pipeline (5 passes):

  Pass 1 — entity discovery (narrow schema: no attributes, no relationships).
  Pass 2 — gap pass: re-scan requirements whose REQ codes were not traced.
  Pass 3 — attributes + relationships (entity-constrained to the Pass 1+2 list).
  Pass 4 — deterministic validation (PK, dangling refs, duplicates, cardinality).
  Pass 5 — LLM critique covering documented failure modes (optional).

Takes the functional RequirementItems (types: functional, data, process) and
produces a domain entity model (MER — Modelo Entidad-Relacion). The Mermaid
erDiagram is rendered deterministically in code from the structured output,
not generated by the LLM, so the diagram is always syntactically valid and
matches the entities/relationships exactly.

Design notes (mirrors classification.py patterns):

- Does NOT write to the DB. Returns a MerResult dataclass consumed by the
  analysis assembler / store layer.
- Uses structured_llm with narrow per-pass schemas for fence-tolerant
  structured output (Z.ai GLM wraps JSON in fences).
- Retry policy: transient (429/5xx/timeout) with exponential backoff, plus
  parse-failure retries (mirrors _classify_item).
- Prompts are in Spanish neutro (no voseo, no spanglish) following project
  conventions for LLM-facing text.
"""
from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field

from backend.agents.llm import structured_llm
from backend.agents.pipelines._diagram_colors import (
    AGGREGATE_ROOT_STROKE,
    BC_PALETTE,
    NETWORK_DEFAULT,
    class_def,
)
from backend.agents.pipelines._resilience import (
    DEFAULT_CONCURRENCY,
    _format_feedback,
    _format_goals,
    _invoke_with_retry,
    _repair_mermaid,
    _validate_mermaid,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# LLM-facing schemas
# ---------------------------------------------------------------------------


class MerAttribute(BaseModel):
    """One attribute of a domain entity."""

    name: str = Field(
        description="Nombre del atributo en camelCase (ej. orderId, createdAt).",
    )
    type: str = Field(
        description=(
            "Tipo de dato del atributo: string, int, float, bool, datetime, "
            "date, uuid, text, json, o el nombre de otra entidad."
        ),
    )
    required: bool = Field(
        default=True,
        description="True si el atributo es obligatorio (NOT NULL).",
    )
    is_key: bool = Field(
        default=False,
        description="True si el atributo es parte de la clave primaria (PK).",
    )
    description: str = Field(
        default="",
        description="Descripcion breve del atributo (opcional).",
    )


class MerEntitySchema(BaseModel):
    """One domain entity identified from the requirements."""

    name: str = Field(
        description=(
            "Nombre de la entidad en PascalCase (ej. SalesOrder, UserAccount, "
            "Invoice). Usar sustantivos del dominio, no tablas de base de datos."
        ),
    )
    description: str = Field(
        default="",
        description="Descripcion de la entidad y su rol en el dominio.",
    )
    attributes: list[MerAttribute] = Field(
        default_factory=list,
        description="Atributos de la entidad. Toda entidad debe tener al menos un PK.",
    )
    aggregate_root: bool = Field(
        default=False,
        description=(
            "True si la entidad es la raiz de un agregado DDD (agrupa otras "
            "entidades y controla el acceso a ellas)."
        ),
    )
    bounded_context: str = Field(
        default="",
        description=(
            "Nombre del contexto delimitado DDD al que pertenece (ej. "
            "'Sales', 'Billing', 'Identity'). Vacio si no aplica."
        ),
    )
    traced_req_codes: list[str] = Field(
        default_factory=list,
        description=(
            "Codigos REQ-XXXX de los requerimientos que justifican esta "
            "entidad. Tomarlos literalmente del input."
        ),
    )


class MerRelationshipSchema(BaseModel):
    """One directed relationship between two domain entities."""

    from_entity: str = Field(
        description="Nombre PascalCase de la entidad origen.",
    )
    to_entity: str = Field(
        description="Nombre PascalCase de la entidad destino.",
    )
    cardinality: str = Field(
        description=(
            'Cardinalidad de la relacion: exactamente uno de "1:1", "1:N", "N:M".'
        ),
    )
    label: str = Field(
        default="",
        description=(
            "Verbo que describe la relacion en infinitivo o presente "
            "(ej. 'has', 'belongs_to', 'contains')."
        ),
    )
    description: str = Field(
        default="",
        description="Descripcion de la relacion (opcional).",
    )
    traced_req_codes: list[str] = Field(
        default_factory=list,
        description=(
            "Codigos REQ-XXXX de los requerimientos que justifican esta "
            "relacion. Tomarlos literalmente del input."
        ),
    )


class MerResultSchema(BaseModel):
    """Wrapper for the MER extraction result (kept for backward compat)."""

    entities: list[MerEntitySchema] = Field(
        default_factory=list,
        description="Entidades de dominio identificadas en los requerimientos.",
    )
    relationships: list[MerRelationshipSchema] = Field(
        default_factory=list,
        description=(
            "Relaciones entre entidades. from_entity y to_entity deben "
            "coincidir con nombres de entidades en el campo entities."
        ),
    )


# ---------------------------------------------------------------------------
# Narrow per-pass schemas (multi-pass pipeline)
# ---------------------------------------------------------------------------


class EntityCandidate(BaseModel):
    """Narrow schema for Pass 1: entity discovery only (no attributes, no relationships)."""

    name: str = Field(description="Nombre PascalCase de la entidad")
    description: str = Field(default="", description="Descripcion breve")
    aggregate_root: bool = Field(default=False)
    bounded_context: str = Field(default="")
    traced_req_codes: list[str] = Field(
        default_factory=list,
        description="Codigos REQ-XXXX que justifican esta entidad",
    )


class EntityDiscoverySchema(BaseModel):
    """Pass 1 and Pass 2 output schema."""

    entities: list[EntityCandidate]


class MerEntityDetail(BaseModel):
    """Pass 3: attributes for a known entity."""

    name: str = Field(
        description="Nombre PascalCase (debe ser una de las entidades listadas)"
    )
    attributes: list[MerAttribute] = Field(default_factory=list)


class MerDetailSchema(BaseModel):
    """Pass 3 output schema."""

    entities: list[MerEntityDetail]
    relationships: list[MerRelationshipSchema]


class MerCritiqueFinding(BaseModel):
    """Pass 5: critic finding."""

    entity_name: str = Field(
        description="Entidad afectada o 'GLOBAL'"
    )
    issue_type: str = Field(
        description="omission | overspecification | role_merge | missing_aggregate | spurious_relationship"
    )
    description: str = Field(description="Descripcion del problema encontrado")
    severity: str = Field(description="blocker | warning | info")


class MerCritiqueSchema(BaseModel):
    """Pass 5 output schema."""

    findings: list[MerCritiqueFinding]


class MerDescriptionSchema(BaseModel):
    """Pass 6: narrative description for the analysis view."""

    description: str = Field(
        description=(
            "Descripcion breve (2-3 oraciones, en español neutro sin "
            "marcadores de genero) del modelo entidad-relacion. Cubre "
            "entidades principales, aggregate roots, relaciones clave y "
            "bounded contexts si los hay."
        ),
    )


# ---------------------------------------------------------------------------
# Prompts (Spanish neutro — no voseo, no spanglish)
# ---------------------------------------------------------------------------

# Original single-pass prompt kept for backward compatibility.
MER_PROMPT = (
    "Eres un analista de diseno de software que construye el Modelo "
    "Entidad-Relacion (MER) del dominio a partir de requerimientos "
    "funcionales.\n\n"
    "Recibiras una lista de requerimientos funcionales (tipos: functional, "
    "data, process) con sus codigos REQ-XXXX y enunciados. Tu tarea es "
    "identificar las entidades de dominio principales, sus atributos clave y "
    "las relaciones entre ellas.\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original de los requerimientos en las "
    "descripciones. NO traduzcas.\n"
    "- Identifica sustantivos del dominio que representan conceptos de negocio "
    "(no tablas de base de datos ni clases de implementacion).\n"
    "- Toda entidad debe tener al menos un atributo marcado como is_key=True.\n"
    "- Las relaciones deben referenciar entidades que existen en el resultado. "
    "No inventes entidades que no aparecen en el campo entities.\n"
    "- traced_req_codes: para cada entidad y relacion, incluye los codigos "
    "REQ-XXXX de los requerimientos que la justifican. Toma los codigos "
    "literalmente del input.\n"
    "- No inventas atributos o relaciones que no se infieran de los "
    "requerimientos. Si un requerimiento no genera una entidad clara, no la "
    "inventes.\n"
    "- aggregate_root: marca como True solo a la entidad que agrupa a otras "
    "dentro de un mismo agregado de dominio (DDD).\n"
    "- bounded_context: asigna un contexto delimitado cuando el dominio sea "
    "suficientemente amplio como para justitar separacion (ej. 'Sales', "
    "'Billing'). Si el dominio es pequeno, deja vacio.\n"
    "- cardinalidad: usa exactamente los valores '1:1', '1:N' o 'N:M'.\n"
    "- Prefiere entidades de grano grueso (que agrupen informacion relacionada) "
    "sobre atributos sueltos.\n\n"
    "Devuelve SOLO el objeto estructurado."
)

_ENTITY_DISCOVERY_PROMPT = (
    "Eres un analista de dominio DDD. Tu UNICA tarea es identificar las entidades "
    "principales del dominio a partir de los requerimientos funcionales. "
    "NO diseñes atributos ni relaciones — solo identifica que entidades existen.\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original de los requerimientos.\n"
    "- Identifica sustantivos del dominio (conceptos de negocio, no tablas de BD).\n"
    "- aggregate_root: marca True solo a entidades que agrupan otras.\n"
    "- bounded_context: asigna cuando el dominio justifique separacion.\n"
    "- traced_req_codes: incluye los REQ-XXXX que justifican cada entidad.\n"
    "- No inventes entidades que no se infieran de los requerimientos.\n"
    "Devuelve SOLO el objeto estructurado."
)

_GAP_PASS_PROMPT = (
    "Eres un analista de dominio. Los siguientes requerimientos NO fueron cubiertos "
    "en la primera pasada de identificacion de entidades. Revisa cada uno y determina "
    "si justifica una entidad nueva del dominio. Si ningun requerimiento genera una "
    "entidad nueva, devuelve una lista vacia.\n"
    "Devuelve SOLO el objeto estructurado."
)

_DETAIL_PROMPT = (
    "Eres un arquitecto de software. Se te da la lista definitiva de entidades del "
    "dominio. Tu tarea es:\n"
    "1. Asignar atributos detallados a cada entidad (con tipo, PK, required).\n"
    "2. Identificar relaciones entre entidades (solo entre las entidades listadas).\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original.\n"
    "- NO inventes entidades nuevas. Solo atributos y relaciones para las entidades dadas.\n"
    "- Toda entidad debe tener al menos un atributo marcado como is_key=True (PK).\n"
    "- Las relaciones deben referenciar SOLO entidades de la lista.\n"
    "- cardinalidad: usa exactamente '1:1', '1:N' o 'N:M'.\n"
    "Devuelve SOLO el objeto estructurado."
)

_CRITIQUE_PROMPT = (
    "Eres un crítico de modelos de dominio. Se te da el MER (entidades + relaciones) "
    "generado a partir de requerimientos. Tu tarea es identificar problemas:\n\n"
    "Categorias de fallo a revisar:\n"
    "1. omission: una entidad importante que deberia existir pero no aparece.\n"
    "2. overspecification: una entidad o relacion inventada que no se justifica.\n"
    "3. role_merge: dos conceptos distintos fusionados en una sola entidad.\n"
    "4. missing_aggregate: un aggregate_root sin invariante claro que proteger.\n"
    "5. spurious_relationship: una relacion que no se deduce de los requerimientos.\n\n"
    "Si el modelo esta correcto, devuelve findings vacio.\n"
    "Devuelve SOLO el objeto estructurado."
)

_MER_DESCRIPTION_PROMPT = (
    "Eres un arquitecto de software. Se te da el MER (entidades + relaciones) "
    "generado a partir de requerimientos. Escribe una descripcion breve del "
    "modelo en prosa (2-3 oraciones).\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original de los requerimientos.\n"
    "- No uses viñetas ni listas — prosa continua.\n"
    "- Menciona las entidades principales y su rol.\n"
    "- Si hay aggregate roots, explica que agrupan.\n"
    "- Si hay bounded contexts, nombralos.\n"
    "- Describe las relaciones mas importantes (cardinalidad + significado).\n"
    "Devuelve SOLO el objeto estructurado."
)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class MerResult:
    """Output of the MER pipeline (entities, relationships, mermaid, stats)."""

    entities: list[MerEntitySchema] = field(default_factory=list)
    relationships: list[MerRelationshipSchema] = field(default_factory=list)
    mermaid: str = ""
    description: str = ""
    stats: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Mermaid erDiagram rendering (deterministic, from structured output)
# ---------------------------------------------------------------------------

# Mermaid erDiagram cardinality notation:
#   1:1  -> ||--||   (exactly one to exactly one)
#   1:N  -> ||--o{   (one to zero-or-many)
#   N:M  -> }o--o{   (zero-or-many to zero-or-many)
_MERMAID_CARDINALITY = {
    "1:1": "||--||",
    "1:N": "||--o{",
    "N:M": "}o--o{",
}


def _mermaid_attr_line(attr: dict) -> str:
    """Render one attribute as a Mermaid erDiagram column line."""
    type_str = attr.get("type", "string")
    name = attr.get("name", "field")
    if attr.get("is_key"):
        return f"    {type_str} {name} PK"
    return f"    {type_str} {name}"


def _render_mermaid(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
) -> str:
    """Render a Mermaid erDiagram from structured entity/relationship output.

    Produces valid Mermaid syntax:
        erDiagram
            ENTITY_A {
                string id PK
                string name
            }
            ENTITY_A ||--o{ ENTITY_B : "has"

    Entity names are sanitized to alphanumeric + underscore (Mermaid
    identifiers). Relationship labels are quoted to allow spaces.

    Each entity is assigned a ``classDef`` color based on its bounded
    context. Aggregate roots receive a gold border (stroke-width 3px).
    Entities without a bounded context get the default gray styling.
    """
    if not entities:
        return "erDiagram"

    lines: list[str] = ["erDiagram"]

    # Entity blocks
    for ent in entities:
        # Mermaid identifiers: uppercase alphanumeric + underscore.
        ent_id = ent.name.replace(" ", "_").upper()
        lines.append(f"    {ent_id} {{")
        for attr in ent.attributes:
            lines.append(_mermaid_attr_line(attr.model_dump()))
        lines.append("    }")

    # Relationship edges
    for rel in relationships:
        from_id = rel.from_entity.replace(" ", "_").upper()
        to_id = rel.to_entity.replace(" ", "_").upper()
        card = _MERMAID_CARDINALITY.get(rel.cardinality.strip(), "||--o{")
        label = rel.label or "relates_to"
        lines.append(f'    {from_id} {card} {to_id} : "{label}"')

    # classDef + class assignments for semantic coloring by bounded context.
    unique_bcs = sorted(
        {e.bounded_context for e in entities if e.bounded_context}
    )
    bc_to_idx: dict[str, int] = {bc: i for i, bc in enumerate(unique_bcs)}
    for i, _bc in enumerate(unique_bcs):
        fill, stroke = BC_PALETTE[i % len(BC_PALETTE)]
        lines.append("    " + class_def(f"bc{i}", fill, stroke))
    # Entities without BC get gray.
    lines.append(
        "    "
        + class_def("bc_default", NETWORK_DEFAULT[0], NETWORK_DEFAULT[1])
    )
    # Aggregate root highlight: gold border, thicker.
    lines.append(
        "    "
        + class_def(
            "agg_root",
            NETWORK_DEFAULT[0],
            AGGREGATE_ROOT_STROKE,
            sw=3,
        )
    )
    for ent in entities:
        ent_id = ent.name.replace(" ", "_").upper()
        if ent.bounded_context and ent.bounded_context in bc_to_idx:
            cls = f"bc{bc_to_idx[ent.bounded_context]}"
        else:
            cls = "bc_default"
        lines.append(f"    class {ent_id} {cls}")
        if ent.aggregate_root:
            lines.append(f"    class {ent_id} agg_root")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cardinality normalization
# ---------------------------------------------------------------------------


def _normalize_cardinality(value: str) -> str:
    """Normalize cardinality strings to the canonical 1:1 / 1:N / N:M forms."""
    v = value.strip().upper().replace(" ", "")
    # Common variants the LLM might emit.
    variants = {
        "1:1": "1:1", "1-1": "1:1", "UNO:AUNO": "1:1", "ONE-TO-ONE": "1:1",
        "1:N": "1:N", "1-N": "1:N", "1:M": "1:N", "ONE-TO-MANY": "1:N",
        "UNO:AN": "1:N", "N:M": "N:M", "N-M": "N:M", "M:N": "N:M", "M-N": "N:M",
        "MANY-TO-MANY": "N:M", "N:AN": "N:M",
    }
    return variants.get(v, "1:N")  # default to 1:N (most common)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _build_items_text(
    items,
    project_name: str = "",
    project_description: str = "",
    goals: list[Any] | None = None,
    feedback: str = "",
) -> str:
    """Build the user message text from functional requirement items."""
    lines: list[str] = []
    if feedback:
        lines.append(_format_feedback(feedback).rstrip())
        lines.append("")
    if goals:
        lines.append(
            _format_goals(goals, section_title="OBJETIVOS DEL SISTEMA").rstrip()
        )
        lines.append("")
    if project_name:
        lines.append(f"PROYECTO: {project_name}")
    if project_description:
        lines.append(f"DESCRIPCION: {project_description}")
    lines.append("")

    for it in items:
        lines.append(f"REQ_CODE: {it.code}")
        lines.append(f"TYPE: {it.type.value}")
        lines.append(f"STATEMENT: {it.statement}")
        if it.source:
            src = it.source
            if isinstance(src, dict):
                quote = src.get("quote") or src.get("section") or ""
            elif isinstance(src, list) and src:
                quote = src[0].get("quote", "") if isinstance(src[0], dict) else str(src[0])
            else:
                quote = str(src)
            if quote:
                lines.append(f"SOURCE: {quote[:300]}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Pass 1: entity discovery (narrow schema)
# ---------------------------------------------------------------------------


async def _discover_entities(
    items,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
) -> list[EntityCandidate]:
    """Pass 1: entity discovery with narrow schema (no attributes, no relationships)."""
    user_text = _build_items_text(
        items, project_name, project_description,
        goals=goals, feedback=feedback,
    )
    msgs = [("system", _ENTITY_DISCOVERY_PROMPT), ("human", user_text)]
    llm = structured_llm(EntityDiscoverySchema)
    try:
        result = await _invoke_with_retry(
            llm, msgs, context_label="mer_discover"
        )
        return list(result.entities)
    except Exception:
        logger.exception("_discover_entities: all retries exhausted")
        return []


# ---------------------------------------------------------------------------
# Pass 2: gap pass for uncovered requirements
# ---------------------------------------------------------------------------


async def _gap_pass(
    items,
    candidates: list[EntityCandidate],
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
) -> list[EntityCandidate]:
    """Pass 2: detect uncovered REQ codes and re-scan them."""
    input_codes = {it.code for it in items}
    covered_codes = {c for e in candidates for c in e.traced_req_codes}
    uncovered = input_codes - covered_codes
    if not uncovered:
        return []

    uncovered_items = [it for it in items if it.code in uncovered]
    user_text = _build_items_text(
        uncovered_items, project_name, project_description,
        goals=goals, feedback=feedback,
    )
    already_listed = ", ".join(e.name for e in candidates) or "(ninguna)"
    user_text += (
        f"\nENTIDADES YA IDENTIFICADAS: {already_listed}\n"
        "Revisa SOLO los requerimientos anteriores y determina si generan "
        "entidades NUEVAS (no listadas arriba).\n"
    )
    msgs = [("system", _GAP_PASS_PROMPT), ("human", user_text)]
    llm = structured_llm(EntityDiscoverySchema)
    try:
        result = await _invoke_with_retry(
            llm, msgs, context_label="mer_gap_pass"
        )
        return list(result.entities)
    except Exception:
        logger.exception("_gap_pass: all retries exhausted")
        return []


# ---------------------------------------------------------------------------
# Pass 3: attributes + relationships (entity-constrained)
# ---------------------------------------------------------------------------


async def _detail_entities_relationships(
    items,
    candidates: list[EntityCandidate],
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
) -> tuple[list[MerEntitySchema], list[MerRelationshipSchema]]:
    """Pass 3: given the finalized entity list, extract attributes + relationships.

    Merges candidate metadata (description, aggregate_root, bounded_context,
    traced_req_codes) with the detail entities (attributes) matched by name
    (case-insensitive). Builds full MerEntitySchema objects from the merged data.
    """
    entity_list_str = "\n".join(f"- {c.name}" for c in candidates)
    user_text = _build_items_text(
        items, project_name, project_description,
        goals=goals, feedback=feedback,
    )
    user_text += (
        f"\nENTIDADES DEL DOMINIO (usa SOLO estos nombres):\n"
        f"{entity_list_str}\n"
    )
    msgs = [("system", _DETAIL_PROMPT), ("human", user_text)]
    llm = structured_llm(MerDetailSchema)
    try:
        detail = await _invoke_with_retry(
            llm, msgs, context_label="mer_detail"
        )
    except Exception:
        logger.exception(
            "_detail_entities_relationships: all retries exhausted"
        )
        # Fallback: return candidates as entities without attributes.
        fallback_entities = [
            MerEntitySchema(
                name=c.name,
                description=c.description,
                aggregate_root=c.aggregate_root,
                bounded_context=c.bounded_context,
                traced_req_codes=c.traced_req_codes,
            )
            for c in candidates
        ]
        return (fallback_entities, [])

    # Merge candidates + detail by lowercase name.
    candidate_lookup = {c.name.lower(): c for c in candidates}
    entities_full: list[MerEntitySchema] = []
    for det_ent in detail.entities:
        c = candidate_lookup.get(det_ent.name.lower())
        if c:
            entities_full.append(
                MerEntitySchema(
                    name=c.name,
                    description=c.description,
                    attributes=det_ent.attributes,
                    aggregate_root=c.aggregate_root,
                    bounded_context=c.bounded_context,
                    traced_req_codes=c.traced_req_codes,
                )
            )
        else:
            # Entity from detail not in candidates — include with empty metadata.
            entities_full.append(
                MerEntitySchema(name=det_ent.name, attributes=det_ent.attributes)
            )

    relationships = list(detail.relationships)
    return (entities_full, relationships)


# ---------------------------------------------------------------------------
# Pass 4: deterministic validation
# ---------------------------------------------------------------------------


def _validate_mer(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
) -> list[str]:
    """Pass 4: deterministic validation checks (no LLM).

    Returns a list of warning strings. Each warning describes one issue found.
    An empty list means the model passed all deterministic checks.
    """
    warnings: list[str] = []
    entity_names_lower = {e.name.lower() for e in entities}

    # Check: no duplicate entity names (case-insensitive).
    seen: set[str] = set()
    for e in entities:
        lower = e.name.lower()
        if lower in seen:
            warnings.append(
                f"Entidad duplicada (ignorando mayusculas): {e.name}"
            )
        seen.add(lower)

    # Check: every entity has at least one PK.
    for e in entities:
        if not any(a.is_key for a in e.attributes):
            warnings.append(
                f"Entidad sin PK (is_key=True): {e.name}"
            )

    # Check: relationships reference existing entities.
    for rel in relationships:
        if rel.from_entity.lower() not in entity_names_lower:
            warnings.append(
                f"Relacion referencia entidad inexistente (from_entity): "
                f"{rel.from_entity}"
            )
        if rel.to_entity.lower() not in entity_names_lower:
            warnings.append(
                f"Relacion referencia entidad inexistente (to_entity): "
                f"{rel.to_entity}"
            )

    # Check: valid cardinality values.
    valid_cardinalities = {"1:1", "1:N", "N:M"}
    for rel in relationships:
        if rel.cardinality not in valid_cardinalities:
            warnings.append(
                f"Cardinalidad invalida '{rel.cardinality}' en relacion "
                f"{rel.from_entity} -> {rel.to_entity}"
            )

    return warnings


# ---------------------------------------------------------------------------
# Pass 5: LLM critique
# ---------------------------------------------------------------------------


async def _critique_mer(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
    items,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
) -> list[MerCritiqueFinding]:
    """Pass 5: LLM critique covering documented failure modes."""
    # Build summaries.
    entity_lines = []
    for e in entities:
        attrs = ", ".join(a.name for a in e.attributes[:5]) or "(sin atributos)"
        entity_lines.append(f"- {e.name} ({attrs})")
    entity_summary = "\n".join(entity_lines) or "(ninguna)"

    rel_lines = []
    for r in relationships:
        rel_lines.append(
            f"- {r.from_entity} {r.cardinality} {r.to_entity}: {r.label}"
        )
    rel_summary = "\n".join(rel_lines) or "(ninguna)"

    req_lines = [f"- {it.code}: {it.statement[:100]}" for it in items[:30]]
    req_summary = "\n".join(req_lines)
    if len(items) > 30:
        req_summary += f"\n... ({len(items) - 30} mas)"

    header_lines = []
    if project_name:
        header_lines.append(f"PROYECTO: {project_name}")
    if project_description:
        header_lines.append(f"DESCRIPCION: {project_description}")
    header = "\n".join(header_lines)

    goals_block = (
        _format_goals(goals, section_title="OBJETIVOS DEL SISTEMA")
        if goals
        else ""
    )

    user_text = (
        f"{header}\n\n"
        f"{goals_block}"
        f"REQUERIMIENTOS ORIGINALES:\n{req_summary}\n\n"
        f"ENTIDADES DEL MER GENERADO:\n{entity_summary}\n\n"
        f"RELACIONES DEL MER GENERADO:\n{rel_summary}\n"
    )
    msgs = [("system", _CRITIQUE_PROMPT), ("human", user_text)]
    llm = structured_llm(MerCritiqueSchema)
    try:
        result = await _invoke_with_retry(
            llm, msgs, context_label="mer_critique"
        )
        return list(result.findings)
    except Exception:
        logger.exception("_critique_mer: all retries exhausted")
        return []


# ---------------------------------------------------------------------------
# Pass 6: narrative description (for analysis view)
# ---------------------------------------------------------------------------


async def _describe_mer(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
    items,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
) -> str:
    """Pass 6: generate a short narrative description of the MER model.

    Returns a prose description (2-3 sentences) or "" on failure.
    The description is shown in the analysis view below the erDiagram.
    """
    entity_lines = []
    for e in entities:
        attrs = ", ".join(a.name for a in e.attributes[:5]) or "(sin atributos)"
        entity_lines.append(f"- {e.name} ({attrs})")
    entity_summary = "\n".join(entity_lines) or "(ninguna)"

    rel_lines = []
    for r in relationships:
        rel_lines.append(
            f"- {r.from_entity} {r.cardinality} {r.to_entity}: {r.label}"
        )
    rel_summary = "\n".join(rel_lines) or "(ninguna)"

    header_lines = []
    if project_name:
        header_lines.append(f"PROYECTO: {project_name}")
    if project_description:
        header_lines.append(f"DESCRIPCION: {project_description}")
    header = "\n".join(header_lines)

    goals_block = (
        _format_goals(goals, section_title="OBJETIVOS DEL SISTEMA")
        if goals
        else ""
    )

    user_text = (
        f"{header}\n\n"
        f"{goals_block}"
        f"ENTIDADES DEL MER:\n{entity_summary}\n\n"
        f"RELACIONES DEL MER:\n{rel_summary}\n"
    )
    msgs = [("system", _MER_DESCRIPTION_PROMPT), ("human", user_text)]
    llm = structured_llm(MerDescriptionSchema)
    try:
        result = await _invoke_with_retry(
            llm, msgs, context_label="mer_describe"
        )
        return result.description
    except Exception:
        logger.exception("_describe_mer: all retries exhausted")
        return ""


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


async def generate_mer(
    items,
    *,
    project_name: str = "",
    project_description: str = "",
    concurrency: int = DEFAULT_CONCURRENCY,
    enable_critique: bool = True,
    goals: list[Any] | None = None,
    feedback: str = "",
) -> MerResult:
    """Generate a domain entity model (MER) from functional requirements.

    Multi-pass pipeline:

      Pass 1 — entity discovery (narrow schema).
      Pass 2 — gap pass for uncovered REQ codes.
      Pass 3 — attributes + relationships (entity-constrained).
      Pass 4 — deterministic validation.
      Pass 5 — LLM critique (optional, enabled by default).

    Takes RequirementItem objects (filtered to functional/data/process types)
    and produces a MerResult with entities, relationships, a Mermaid erDiagram
    string rendered deterministically from the structured LLM output, plus
    validation warnings and critique findings in stats.

    Each pass has its own retry loop (transient backoff + parse retries,
    mirroring classification._classify_item). Failed passes degrade
    gracefully — a failed gap pass returns no extra candidates, a failed
    critique returns no findings — instead of aborting the whole pipeline.
    """
    if not items:
        return MerResult(stats={"input": 0})

    # Pass 1: entity discovery.
    candidates = await _discover_entities(
        items, project_name, project_description,
        goals=goals, feedback=feedback,
    )

    # Pass 2: gap pass for uncovered requirements.
    gap_candidates = await _gap_pass(
        items, candidates, project_name, project_description,
        goals=goals, feedback=feedback,
    )
    all_candidates = candidates + gap_candidates

    # Pass 3: attributes + relationships (entity-constrained).
    entities_full, relationships = await _detail_entities_relationships(
        items, all_candidates, project_name, project_description,
        goals=goals, feedback=feedback,
    )

    # Normalize cardinalities to canonical forms before validation/rendering.
    for rel in relationships:
        rel.cardinality = _normalize_cardinality(rel.cardinality)

    # Pass 4: deterministic validation.
    warnings = _validate_mer(entities_full, relationships)

    # Pass 5: LLM critique (optional).
    critique_findings: list[MerCritiqueFinding] = []
    if enable_critique:
        critique_findings = await _critique_mer(
            entities_full, relationships, items, project_name,
            project_description, goals=goals,
        )

    # Pass 6: narrative description (lightweight, always runs).
    description = await _describe_mer(
        entities_full, relationships, items, project_name,
        project_description, goals=goals,
    )

    # Render Mermaid erDiagram deterministically.
    mermaid = _render_mermaid(entities_full, relationships)

    # Compute coverage stats.
    input_codes = {it.code for it in items}
    covered_codes = {c for e in entities_full for c in e.traced_req_codes}
    uncovered = input_codes - covered_codes

    stats = {
        "input": len(items),
        "entities": len(entities_full),
        "relationships": len(relationships),
        "aggregate_roots": sum(1 for e in entities_full if e.aggregate_root),
        "bounded_contexts": len(
            {e.bounded_context for e in entities_full if e.bounded_context}
        ),
        "req_coverage": f"{len(covered_codes)}/{len(input_codes)}",
        "uncovered_codes": sorted(uncovered),
        "gap_pass_found": len(gap_candidates),
        "validation_warnings": warnings,
        "critique_findings": [f.model_dump() for f in critique_findings],
        "critique_blockers": sum(
            1 for f in critique_findings if f.severity == "blocker"
        ),
    }
    logger.info(
        "generate_mer: %d items -> %d entities, %d relationships "
        "(gap +%d, %d warnings, %d critique findings)",
        stats["input"],
        stats["entities"],
        stats["relationships"],
        stats["gap_pass_found"],
        len(warnings),
        len(critique_findings),
    )
    return MerResult(
        entities=entities_full,
        relationships=relationships,
        mermaid=mermaid,
        description=description,
        stats=stats,
    )
