"""MER pipeline: domain entity model extraction from functional requirements.

Multi-pass pipeline (5 passes):

  Pass 1 — entity discovery (narrow schema, batched over items).
  Pass 2 — gap pass: re-scan (batched) requirements whose REQ codes were not
  traced.
  Pass 3 — attributes + relationships (entity-constrained, batched over
  entities).
  Pass 4 — deterministic validation (PK, dangling refs, duplicates, cardinality).
  Pass 5 — LLM critique covering documented failure modes (optional).

Takes the functional RequirementItems (types: functional, data, process) and
produces a domain entity model (MER — Modelo Entidad-Relacion). The Mermaid
erDiagram is rendered deterministically in code from the structured output,
not generated by the LLM, so the diagram is always syntactically valid and
matches the entities/relationships exactly.

Design notes (mirrors classification.py patterns):

- Does NOT write to the DB. Returns a MerResult dataclass consumed by the
  analysis assembler / store layer.
- Uses structured_llm with narrow per-pass schemas for fence-tolerant
  structured output (Z.ai GLM wraps JSON in fences).
- Retry policy: transient (429/5xx/timeout) with exponential backoff, plus
  parse-failure retries (mirrors _classify_item).
- Prompts are in Spanish neutro (no voseo, no spanglish) following project
  conventions for LLM-facing text.
"""
from __future__ import annotations

import asyncio
import logging
import os
import re
import unicodedata
from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field

from backend.agents.llm import structured_llm
from backend.agents.pipelines._diagram_colors import (
    AGGREGATE_ROOT_STROKE,
    BC_PALETTE,
    NETWORK_DEFAULT,
    class_def,
)
from backend.agents.pipelines._resilience import (
    DEFAULT_CONCURRENCY,
    _chunk,
    _format_feedback,
    _format_goals,
    _invoke_with_retry,
    _repair_mermaid,
    _validate_mermaid,
    invoke_structured_resilient,
)

logger = logging.getLogger(__name__)

# Batch size for the discovery / gap passes (narrow schema, small output per
# item). Env-tunable for calibration.
_MER_BATCH_SIZE = int(os.environ.get("INFOFACT_MER_BATCH", "25"))

# Batch size for the detail pass (attributes + relationships). The OUTPUT per
# entity is fat (attributes with types/descriptions + PK/required flags), so a
# large batch overflows the completion budget and the JSON gets truncated
# (finish_reason=length) — session 19 of Planitrack2.0 burned hours in retry
# loops on 25-entity batches. Each batch emits the FULL entity list (so
# cross-batch relationships still validate) but only details its own entities.
_MER_DETAIL_BATCH_SIZE = int(
    os.environ.get("INFOFACT_MER_DETAIL_BATCH", "8")
)


# ---------------------------------------------------------------------------
# LLM-facing schemas
# ---------------------------------------------------------------------------


class MerAttribute(BaseModel):
    """One attribute of a domain entity."""

    name: str = Field(
        description="Nombre del atributo en camelCase (ej. orderId, createdAt).",
    )
    type: str = Field(
        description=(
            "Tipo de dato del atributo: string, int, float, bool, datetime, "
            "date, uuid, text, json, o el nombre de otra entidad."
        ),
    )
    required: bool = Field(
        default=True,
        description="True si el atributo es obligatorio (NOT NULL).",
    )
    length: str = Field(
        default="",
        description=(
            "Largo o precision del atributo cuando el tipo lo soporta "
            "(ej. '16' para un string de 16 caracteres, '10,2' para un "
            "float con 2 decimales). Vacio en tipos que no lo usan."
        ),
    )
    is_key: bool = Field(
        default=False,
        description="True si el atributo es parte de la clave primaria (PK).",
    )
    description: str = Field(
        default="",
        description="Descripcion de negocio breve del atributo (opcional).",
    )


class MerEntitySchema(BaseModel):
    """One domain entity identified from the requirements."""

    name: str = Field(
        description=(
            "Nombre de la entidad en PascalCase (ej. SalesOrder, UserAccount, "
            "Invoice). Usar sustantivos del dominio, no tablas de base de datos."
        ),
    )
    description: str = Field(
        default="",
        description="Descripcion de la entidad y su rol en el dominio.",
    )
    attributes: list[MerAttribute] = Field(
        default_factory=list,
        description="Atributos de la entidad. Toda entidad debe tener al menos un PK.",
    )
    aggregate_root: bool = Field(
        default=False,
        description=(
            "True si la entidad es la raiz de un agregado DDD (agrupa otras "
            "entidades y controla el acceso a ellas)."
        ),
    )
    bounded_context: str = Field(
        default="",
        description=(
            "Nombre del contexto delimitado DDD al que pertenece (ej. "
            "'Sales', 'Billing', 'Identity'). Vacio si no aplica."
        ),
    )
    traced_req_codes: list[str] = Field(
        default_factory=list,
        description=(
            "Codigos REQ-XXXX de los requerimientos que justifican esta "
            "entidad. Tomarlos literalmente del input."
        ),
    )


class MerRelationshipSchema(BaseModel):
    """One directed relationship between two domain entities."""

    from_entity: str = Field(
        description="Nombre PascalCase de la entidad origen.",
    )
    to_entity: str = Field(
        description="Nombre PascalCase de la entidad destino.",
    )
    cardinality: str = Field(
        description=(
            'Cardinalidad de la relacion: exactamente uno de "1:1", "1:N", "N:M".'
        ),
    )
    label: str = Field(
        default="",
        description=(
            "Verbo que describe la relacion en infinitivo o presente "
            "(ej. 'has', 'belongs_to', 'contains')."
        ),
    )
    description: str = Field(
        default="",
        description="Descripcion de la relacion (opcional).",
    )
    traced_req_codes: list[str] = Field(
        default_factory=list,
        description=(
            "Codigos REQ-XXXX de los requerimientos que justifican esta "
            "relacion. Tomarlos literalmente del input."
        ),
    )


class MerResultSchema(BaseModel):
    """Wrapper for the MER extraction result (kept for backward compat)."""

    entities: list[MerEntitySchema] = Field(
        default_factory=list,
        description="Entidades de dominio identificadas en los requerimientos.",
    )
    relationships: list[MerRelationshipSchema] = Field(
        default_factory=list,
        description=(
            "Relaciones entre entidades. from_entity y to_entity deben "
            "coincidir con nombres de entidades en el campo entities."
        ),
    )


# ---------------------------------------------------------------------------
# Narrow per-pass schemas (multi-pass pipeline)
# ---------------------------------------------------------------------------


class EntityCandidate(BaseModel):
    """Narrow schema for Pass 1: entity discovery only (no attributes, no relationships)."""

    name: str = Field(description="Nombre PascalCase de la entidad")
    description: str = Field(default="", description="Descripcion breve")
    aggregate_root: bool = Field(default=False)
    bounded_context: str = Field(default="")
    traced_req_codes: list[str] = Field(
        default_factory=list,
        description="Codigos REQ-XXXX que justifican esta entidad",
    )


class EntityDiscoverySchema(BaseModel):
    """Pass 1 and Pass 2 output schema."""

    entities: list[EntityCandidate]


class MerEntityDetail(BaseModel):
    """Pass 3: attributes for a known entity."""

    name: str = Field(
        description="Nombre PascalCase (debe ser una de las entidades listadas)"
    )
    attributes: list[MerAttribute] = Field(default_factory=list)


class MerDetailSchema(BaseModel):
    """Pass 3 output schema."""

    entities: list[MerEntityDetail]
    relationships: list[MerRelationshipSchema]


class MerCritiqueFinding(BaseModel):
    """Pass 5: critic finding."""

    entity_name: str = Field(
        description="Entidad afectada o 'GLOBAL'"
    )
    issue_type: str = Field(
        description="omission | overspecification | role_merge | missing_aggregate | spurious_relationship"
    )
    description: str = Field(description="Descripcion del problema encontrado")
    severity: str = Field(description="blocker | warning | info")


class MerCritiqueSchema(BaseModel):
    """Pass 5 output schema."""

    findings: list[MerCritiqueFinding]


class MerConsolidationGroup(BaseModel):
    """One proposed merge: ``keep`` absorbs the entities in ``absorb``."""

    keep: str = Field(
        description=(
            "Nombre EXACTO de la entidad que se conserva (debe ser una de "
            "las recibidas)."
        ),
    )
    absorb: list[str] = Field(
        default_factory=list,
        description=(
            "Nombres EXACTOS de las entidades que se fusionan dentro de "
            "keep (cada una debe estar en la lista recibida)."
        ),
    )
    reason: str = Field(
        default="",
        description="Razon breve de la fusion (1 oracion).",
    )


class MerConsolidationSchema(BaseModel):
    """Output schema of the consolidation pass (Pass 3b)."""

    merges: list[MerConsolidationGroup] = Field(
        default_factory=list,
    )


# Env kill-switch: INFOFACT_MER_CONSOLIDATE=0 desactiva el afinamiento.
_MER_CONSOLIDATE_ENABLED = (
    os.environ.get("INFOFACT_MER_CONSOLIDATE", "1") != "0"
)
_MER_CONSOLIDATION_BATCH_SIZE = int(
    os.environ.get("INFOFACT_MER_CONSOLIDATION_BATCH", "25")
)

# Pass 3c: higiene de contextos acotados. INFOFACT_MER_CONTEXT_CONSOLIDATE=0
# desactiva el mapeo LLM (la normalizacion ortografica siempre corre);
# INFOFACT_MER_CONTEXT_MAX fija el techo de etiquetas a partir del cual conviene
# consolidar semanticamente.
_MER_CONTEXT_CONSOLIDATE_ENABLED = (
    os.environ.get("INFOFACT_MER_CONTEXT_CONSOLIDATE", "1") != "0"
)
_MER_CONTEXT_TARGET_MAX = int(
    os.environ.get("INFOFACT_MER_CONTEXT_MAX", "25")
)


class MerContextMapping(BaseModel):
    """Una entrada del mapeo de contextos: etiqueta cruda -> canonica."""

    raw: str = Field(
        description="Etiqueta de contexto original, copiada de la lista de entrada."
    )
    canonical: str = Field(
        description="Etiqueta canonica que la reemplaza (debe existir en la lista)."
    )


class MerContextConsolidationSchema(BaseModel):
    """Output schema del mapeo de contextos acotados (Pass 3c)."""

    mappings: list[MerContextMapping] = Field(default_factory=list)


_MER_CONTEXT_CONSOLIDATION_PROMPT = """Eres un arquitecto de software que consolida los contextos acotados (bounded contexts) de un modelo de dominio.
Recibes la lista de etiquetas de contexto asignadas a las entidades de UN mismo modelo, con la cantidad de entidades de cada una. Estan fragmentadas: sinonimos, plurales, variantes con o sin espacios, traducciones parciales.
Devuelve un mapeo que fusione etiquetas que pertenecen al MISMO contexto de negocio. Reglas:
- La etiqueta canonica debe ser una de las etiquetas de la lista, copiada tal cual.
- Solo fusiona sinonimos reales o subconjuntos evidentes (ej. «Comunicación» -> «Comunicaciones»); NO fusiones dominios de negocio distintos (ej. «Navegación» y «Ruteo» pueden ser contextos separados).
- Las etiquetas que ya son correctas no necesitan entrada en el mapeo.
- Objetivo: quedar con un catalogo chico de contextos canonicos (idealmente entre 8 y 25) sin perder distinciones de negocio relevantes."""


class MerDescriptionSchema(BaseModel):
    """Pass 6: narrative description for the analysis view."""

    description: str = Field(
        description=(
            "Descripcion breve (2-3 oraciones, en español neutro sin "
            "marcadores de genero) del modelo entidad-relacion. Cubre "
            "entidades principales, aggregate roots, relaciones clave y "
            "bounded contexts si los hay."
        ),
    )


# ---------------------------------------------------------------------------
# Prompts (Spanish neutro — no voseo, no spanglish)
# ---------------------------------------------------------------------------

# Original single-pass prompt kept for backward compatibility.
MER_PROMPT = (
    "Eres un analista de diseno de software que construye el Modelo "
    "Entidad-Relacion (MER) del dominio a partir de requerimientos "
    "funcionales.\n\n"
    "Recibiras una lista de requerimientos funcionales (tipos: functional, "
    "data, process) con sus codigos REQ-XXXX y enunciados. Tu tarea es "
    "identificar las entidades de dominio principales, sus atributos clave y "
    "las relaciones entre ellas.\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original de los requerimientos en las "
    "descripciones. NO traduzcas.\n"
    "- Identifica sustantivos del dominio que representan conceptos de negocio "
    "(no tablas de base de datos ni clases de implementacion).\n"
    "- Toda entidad debe tener al menos un atributo marcado como is_key=True.\n"
    "- Las relaciones deben referenciar entidades que existen en el resultado. "
    "No inventes entidades que no aparecen en el campo entities.\n"
    "- traced_req_codes: para cada entidad y relacion, incluye los codigos "
    "REQ-XXXX de los requerimientos que la justifican. Toma los codigos "
    "literalmente del input.\n"
    "- No inventas atributos o relaciones que no se infieran de los "
    "requerimientos. Si un requerimiento no genera una entidad clara, no la "
    "inventes.\n"
    "- aggregate_root: marca como True solo a la entidad que agrupa a otras "
    "dentro de un mismo agregado de dominio (DDD).\n"
    "- bounded_context: asigna un contexto delimitado cuando el dominio sea "
    "suficientemente amplio como para justitar separacion (ej. 'Sales', "
    "'Billing'). Si el dominio es pequeno, deja vacio.\n"
    "- cardinalidad: usa exactamente los valores '1:1', '1:N' o 'N:M'.\n"
    "- Prefiere entidades de grano grueso (que agrupen informacion relacionada) "
    "sobre atributos sueltos.\n\n"
    "Devuelve SOLO el objeto estructurado."
)

_ENTITY_DISCOVERY_PROMPT = (
    "Eres un analista de dominio DDD. Tu UNICA tarea es identificar las entidades "
    "principales del dominio a partir de los requerimientos funcionales. "
    "NO diseñes atributos ni relaciones — solo identifica que entidades existen.\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original de los requerimientos.\n"
    "- Identifica sustantivos del dominio (conceptos de negocio, no tablas de BD).\n"
    "- aggregate_root: marca True solo a entidades que agrupan otras.\n"
    "- bounded_context: asigna cuando el dominio justifique separacion.\n"
    "- traced_req_codes: incluye los REQ-XXXX que justifican cada entidad.\n"
    "- No inventes entidades que no se infieran de los requerimientos.\n"
    "Devuelve SOLO el objeto estructurado."
)

_GAP_PASS_PROMPT = (
    "Eres un analista de dominio. Los siguientes requerimientos NO fueron cubiertos "
    "en la primera pasada de identificacion de entidades. Revisa cada uno y determina "
    "si justifica una entidad nueva del dominio. Si ningun requerimiento genera una "
    "entidad nueva, devuelve una lista vacia.\n"
    "Devuelve SOLO el objeto estructurado."
)

_DETAIL_PROMPT = (
    "Eres un arquitecto de software. Se te da la lista definitiva de entidades del "
    "dominio. Tu tarea es:\n"
    "1. Asignar atributos detallados a cada entidad (con tipo, largo, PK, required).\n"
    "2. Identificar relaciones entre entidades (solo entre las entidades listadas).\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original.\n"
    "- ECONOMIA DE SALIDA: la lista de entidades puede ser larga y solo debes "
    "detallar las entidades que se indiquen; para el resto NO emitas entradas.\n"
    "- length: SOLO cuando el tipo lo soporta (string -> caracteres maximos, "
    "ej. '16'; float -> 'precision,escala', ej. '10,2'). Dejalo vacio en int, "
    "bool, datetime, date, uuid, text y json. Nunca inventes largos que los "
    "requerimientos no sugieran.\n"
    "- description de cada atributo: UNA frase breve de negocio (maximo 120 "
    "caracteres) que diga que representa; si el atributo tiene valores "
    "permitidos (enum), enumerarlos dentro de la description (ej. 'Estado del "
    "pedido: activa, cancelada, cumplida'). La salida debe seguir siendo "
    "compacta.\n"
    "- NO inventes entidades nuevas. Solo atributos y relaciones para las entidades indicadas.\n"
    "- Toda entidad detallada debe tener al menos un atributo marcado como is_key=True (PK).\n"
    "- Las relaciones deben referenciar SOLO entidades de la lista.\n"
    "- cardinalidad: usa exactamente '1:1', '1:N' o 'N:M'.\n"
    "Devuelve SOLO el objeto estructurado."
)

_CRITIQUE_PROMPT = (
    "Eres un crítico de modelos de dominio. Se te da el MER (entidades + relaciones) "
    "generado a partir de requerimientos. Tu tarea es identificar problemas:\n\n"
    "Categorias de fallo a revisar:\n"
    "1. omission: una entidad importante que deberia existir pero no aparece.\n"
    "2. overspecification: una entidad o relacion inventada que no se justifica.\n"
    "3. role_merge: dos conceptos distintos fusionados en una sola entidad.\n"
    "4. missing_aggregate: un aggregate_root sin invariante claro que proteger.\n"
    "5. spurious_relationship: una relacion que no se deduce de los requerimientos.\n\n"
    "Si el modelo esta correcto, devuelve findings vacio.\n"
    "Devuelve SOLO el objeto estructurado."
)

_MER_DESCRIPTION_PROMPT = (
    "Eres un arquitecto de software. Se te da el MER (entidades + relaciones) "
    "generado a partir de requerimientos. Escribe una descripcion breve del "
    "modelo en prosa (2-3 oraciones).\n\n"
    "Reglas:\n"
    "- IDIOMA: manten el idioma original de los requerimientos.\n"
    "- No uses viñetas ni listas — prosa continua.\n"
    "- Menciona las entidades principales y su rol.\n"
    "- Si hay aggregate roots, explica que agrupan.\n"
    "- Si hay bounded contexts, nombralos.\n"
    "- Describe las relaciones mas importantes (cardinalidad + significado).\n"
    "Devuelve SOLO el objeto estructurado."
)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class MerResult:
    """Output of the MER pipeline (entities, relationships, mermaid, stats)."""

    entities: list[MerEntitySchema] = field(default_factory=list)
    relationships: list[MerRelationshipSchema] = field(default_factory=list)
    mermaid: str = ""
    description: str = ""
    stats: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Mermaid erDiagram rendering (deterministic, from structured output)
# ---------------------------------------------------------------------------

# Mermaid erDiagram cardinality notation:
#   1:1  -> ||--||   (exactly one to exactly one)
#   1:N  -> ||--o{   (one to zero-or-many)
#   N:M  -> }o--o{   (zero-or-many to zero-or-many)
_MERMAID_CARDINALITY = {
    "1:1": "||--||",
    "1:N": "||--o{",
    "N:M": "}o--o{",
}


def _mermaid_attr_line(attr: dict) -> str:
    """Render one attribute as a Mermaid erDiagram column line."""
    type_str = attr.get("type", "string")
    name = attr.get("name", "field")
    if attr.get("is_key"):
        return f"    {type_str} {name} PK"
    return f"    {type_str} {name}"


def _render_mermaid(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
) -> str:
    """Render a Mermaid erDiagram from structured entity/relationship output.

    Produces valid Mermaid syntax:
        erDiagram
            ENTITY_A {
                string id PK
                string name
            }
            ENTITY_A ||--o{ ENTITY_B : "has"

    Entity names are sanitized to alphanumeric + underscore (Mermaid
    identifiers). Relationship labels are quoted to allow spaces.

    Each entity is assigned a ``classDef`` color based on its bounded
    context. Aggregate roots receive a gold border (stroke-width 3px).
    Entities without a bounded context get the default gray styling.
    """
    if not entities:
        return "erDiagram"

    lines: list[str] = ["erDiagram"]

    # Entity blocks
    for ent in entities:
        # Mermaid identifiers: uppercase alphanumeric + underscore.
        ent_id = ent.name.replace(" ", "_").upper()
        lines.append(f"    {ent_id} {{")
        for attr in ent.attributes:
            lines.append(_mermaid_attr_line(attr.model_dump()))
        lines.append("    }")

    # Relationship edges. Los extremos deben ser entidades declaradas:
    # Mermaid auto-crearia un nodo fantasma (caja sin atributos) para cualquier
    # extremo no declarado, invisible para el diccionario de datos.
    valid_ids = {e.name.replace(" ", "_").upper() for e in entities}
    for rel in relationships:
        from_id = rel.from_entity.replace(" ", "_").upper()
        to_id = rel.to_entity.replace(" ", "_").upper()
        if from_id not in valid_ids or to_id not in valid_ids:
            continue
        card = _MERMAID_CARDINALITY.get(rel.cardinality.strip(), "||--o{")
        label = rel.label or "relates_to"
        lines.append(f'    {from_id} {card} {to_id} : "{label}"')

    # classDef + class assignments for semantic coloring by bounded context.
    unique_bcs = sorted(
        {e.bounded_context for e in entities if e.bounded_context}
    )
    bc_to_idx: dict[str, int] = {bc: i for i, bc in enumerate(unique_bcs)}
    for i, _bc in enumerate(unique_bcs):
        fill, stroke = BC_PALETTE[i % len(BC_PALETTE)]
        lines.append("    " + class_def(f"bc{i}", fill, stroke))
    # Entities without BC get gray.
    lines.append(
        "    "
        + class_def("bc_default", NETWORK_DEFAULT[0], NETWORK_DEFAULT[1])
    )
    # Aggregate root highlight: gold border, thicker.
    lines.append(
        "    "
        + class_def(
            "agg_root",
            NETWORK_DEFAULT[0],
            AGGREGATE_ROOT_STROKE,
            sw=3,
        )
    )
    for ent in entities:
        ent_id = ent.name.replace(" ", "_").upper()
        if ent.bounded_context and ent.bounded_context in bc_to_idx:
            cls = f"bc{bc_to_idx[ent.bounded_context]}"
        else:
            cls = "bc_default"
        lines.append(f"    class {ent_id} {cls}")
        if ent.aggregate_root:
            lines.append(f"    class {ent_id} agg_root")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Data dictionary rendering (deterministic, 0 LLM)
# ---------------------------------------------------------------------------


def _md_cell(text: str) -> str:
    """Sanitiza una celda de tabla markdown (sin saltos, pipes escapados)."""
    return text.strip().replace("\n", " ").replace("|", "\\|")


def render_data_dictionary(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
) -> str:
    """Renderiza el diccionario de datos como Markdown (determinista, 0 LLM).

    Formato de referencia para entregables de modelado (Silverston,
    dbdocs/dbt): catálogo de entidades como índice, luego UNA sección por
    entidad con su explicación de negocio y la tabla de campos
    (Campo/Tipo/Largo/Obligatorio/Clave/Descripción) ordenada PK primero,
    luego FKs (atributo cuyo tipo nombra otra entidad) y después atributos
    propios. Cierra con la tabla resumen de relaciones. Tolerante a dicts
    de atributos persistidos sin ``length`` (columna vacía).
    """
    names_lower = {e.name.lower(): e.name for e in entities}

    def _is_fk(attr: MerAttribute) -> bool:
        return (attr.type or "").strip().lower() in names_lower

    lines: list[str] = ["## Diccionario de datos", ""]
    lines.append(
        f"{len(entities)} entidades · "
        f"{sum(len(e.attributes) for e in entities)} atributos · "
        f"{len(relationships)} relaciones"
    )
    lines.append("")

    # Catálogo de entidades (índice del documento).
    lines.append("| Entidad | Descripción | Campos |")
    lines.append("| --- | --- | --- |")
    for ent in entities:
        desc = (ent.description or "").strip()
        cut = desc.find(".")
        if cut > 0:
            desc = desc[: cut + 1]
        lines.append(
            f"| {ent.name} | {_md_cell(desc)} | {len(ent.attributes)} |"
        )
    lines.append("")

    # Una sección por entidad.
    for ent in entities:
        badges: list[str] = []
        if ent.aggregate_root:
            badges.append("aggregate root")
        if ent.bounded_context:
            badges.append(f"contexto: {ent.bounded_context}")
        badge_str = f" ({'; '.join(badges)})" if badges else ""
        lines.append(f"### {ent.name}{badge_str}")
        lines.append("")
        if ent.description:
            lines.append(ent.description.strip())
            lines.append("")
        if not ent.attributes:
            lines.append("_Sin atributos modelados._")
            lines.append("")
            continue
        lines.append("| Campo | Tipo | Largo | Obligatorio | Clave | Descripción |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        # Orden de referencia: PK primero, luego FKs, luego atributos propios.
        ranked = sorted(
            ent.attributes,
            key=lambda a: 0 if a.is_key else 1 if _is_fk(a) else 2,
        )
        for attr in ranked:
            if attr.is_key:
                key = "PK"
            elif _is_fk(attr):
                target = names_lower[(attr.type or "").strip().lower()]
                key = f"FK → {target}"
            else:
                key = ""
            lines.append(
                f"| {attr.name} | {attr.type} | {attr.length or ''} "
                f"| {'sí' if attr.required else 'no'} | {key} "
                f"| {_md_cell(attr.description or '')} |"
            )
        lines.append("")

    # Resumen de relaciones.
    if relationships:
        lines.append("### Relaciones")
        lines.append("")
        lines.append("| Origen | Cardinalidad | Destino | Verbo | Descripción |")
        lines.append("| --- | --- | --- | --- | --- |")
        for rel in relationships:
            lines.append(
                f"| {rel.from_entity} | {rel.cardinality} | {rel.to_entity} "
                f"| {_md_cell(rel.label or '')} "
                f"| {_md_cell(rel.description or '')} |"
            )
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Cardinality normalization
# ---------------------------------------------------------------------------


def _normalize_cardinality(value: str) -> str:
    """Normalize cardinality strings to the canonical 1:1 / 1:N / N:M forms."""
    v = value.strip().upper().replace(" ", "")
    # Common variants the LLM might emit.
    variants = {
        "1:1": "1:1", "1-1": "1:1", "UNO:AUNO": "1:1", "ONE-TO-ONE": "1:1",
        "1:N": "1:N", "1-N": "1:N", "1:M": "1:N", "ONE-TO-MANY": "1:N",
        "UNO:AN": "1:N", "N:M": "N:M", "N-M": "N:M", "M:N": "N:M", "M-N": "N:M",
        "MANY-TO-MANY": "N:M", "N:AN": "N:M",
    }
    return variants.get(v, "1:N")  # default to 1:N (most common)


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def _build_items_text(
    items,
    project_name: str = "",
    project_description: str = "",
    goals: list[Any] | None = None,
    feedback: str = "",
) -> str:
    """Build the user message text from functional requirement items."""
    lines: list[str] = []
    if feedback:
        lines.append(_format_feedback(feedback).rstrip())
        lines.append("")
    if goals:
        lines.append(
            _format_goals(goals, section_title="OBJETIVOS DEL SISTEMA").rstrip()
        )
        lines.append("")
    if project_name:
        lines.append(f"PROYECTO: {project_name}")
    if project_description:
        lines.append(f"DESCRIPCION: {project_description}")
    lines.append("")

    for it in items:
        lines.append(f"REQ_CODE: {it.code}")
        lines.append(f"TYPE: {it.type.value}")
        lines.append(f"STATEMENT: {it.statement}")
        if it.source:
            src = it.source
            if isinstance(src, dict):
                quote = src.get("quote") or src.get("section") or ""
            elif isinstance(src, list) and src:
                quote = src[0].get("quote", "") if isinstance(src[0], dict) else str(src[0])
            else:
                quote = str(src)
            if quote:
                lines.append(f"SOURCE: {quote[:300]}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Pass 1: entity discovery (narrow schema)
# ---------------------------------------------------------------------------


def _dedupe_candidates(
    candidates: list[EntityCandidate],
) -> list[EntityCandidate]:
    """Merge entity candidates found across batches (case-insensitive name).

    The first occurrence wins for description/aggregate_root/bounded_context;
    traced_req_codes are unioned so the same entity reported by two batches
    does not become two entities (it would duplicate the erDiagram block).
    """
    merged: dict[str, EntityCandidate] = {}
    order: list[str] = []
    for c in candidates:
        key = c.name.lower().strip()
        if key in merged:
            existing = merged[key]
            for code in c.traced_req_codes:
                if code not in existing.traced_req_codes:
                    existing.traced_req_codes.append(code)
        else:
            merged[key] = c
            order.append(key)
    return [merged[k] for k in order]


async def _discover_entities_batch(
    items_batch,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
) -> list[EntityCandidate]:
    """Discover entities for a single batch of items (one LLM call)."""
    user_text = _build_items_text(
        items_batch, project_name, project_description,
        goals=goals, feedback=feedback,
    )
    msgs = [("system", _ENTITY_DISCOVERY_PROMPT), ("human", user_text)]
    try:
        result = await invoke_structured_resilient(
            lambda **kw: structured_llm(EntityDiscoverySchema, **kw),
            msgs,
            context_label=f"mer_discover ({len(items_batch)} items)",
        )
        return list(result.entities)
    except Exception:
        logger.exception(
            "_discover_entities_batch: all retries exhausted for %d items",
            len(items_batch),
        )
        return []


async def _discover_entities(
    items,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
    concurrency: int = DEFAULT_CONCURRENCY,
    on_progress=None,
) -> list[EntityCandidate]:
    """Pass 1: batched entity discovery with narrow schema.

    Items are split into batches of ``_MER_BATCH_SIZE`` so a large corpus
    never overflows a single structured call. Batches run concurrently up to
    ``concurrency`` parallel calls; a failed batch degrades to no candidates
    instead of aborting the pass. Duplicate entity names across batches are
    merged by ``_dedupe_candidates``. ``on_progress`` (optional) fires per
    batch for live UI feedback — at corporate scale this pass alone issues
    dozens of calls and is the longest silent stretch of the stage.
    """
    batches = list(_chunk(items, _MER_BATCH_SIZE))
    total = len(batches)
    if total <= 1:
        if on_progress is not None:
            await on_progress("entidades identificadas (1/1 lote)")
        return _dedupe_candidates(
            await _discover_entities_batch(
                items, project_name, project_description,
                goals=goals, feedback=feedback,
            )
        )
    sem = asyncio.Semaphore(concurrency)
    done = 0
    failed = 0

    async def _guarded(batch):
        nonlocal done, failed
        async with sem:
            result = await _discover_entities_batch(
                batch, project_name, project_description,
                goals=goals, feedback=feedback,
            )
            done += 1
            if not result:
                failed += 1
            if on_progress is not None:
                await on_progress(
                    f"entidades identificadas ({done}/{total} lotes)"
                )
            return result

    results = await asyncio.gather(
        *[_guarded(b) for b in batches], return_exceptions=True
    )
    all_candidates: list[EntityCandidate] = []
    for i, r in enumerate(results):
        if isinstance(r, Exception):
            logger.warning(
                "_discover_entities: batch %d/%d failed: %s",
                i + 1, total, r,
            )
            failed += 1
            continue
        all_candidates.extend(r)
    logger.info(
        "mer_discover: %d/%d lotes ok (%d sin candidatos) sobre %d items",
        total - failed, total, failed, len(items),
    )
    return _dedupe_candidates(all_candidates)


# ---------------------------------------------------------------------------
# Pass 2: gap pass for uncovered requirements
# ---------------------------------------------------------------------------


async def _gap_pass(
    items,
    candidates: list[EntityCandidate],
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
    concurrency: int = DEFAULT_CONCURRENCY,
    on_progress=None,
) -> list[EntityCandidate]:
    """Pass 2: detect uncovered REQ codes and re-scan them (batched).

    With a large corpus the uncovered set can hold hundreds of items, so the
    rescan itself runs in batches of ``_MER_BATCH_SIZE``. ``on_progress``
    (optional) fires per batch for live UI feedback.
    """
    input_codes = {it.code for it in items}
    covered_codes = {c for e in candidates for c in e.traced_req_codes}
    uncovered = input_codes - covered_codes
    if not uncovered:
        return []

    uncovered_items = [it for it in items if it.code in uncovered]
    already_listed = ", ".join(e.name for e in candidates) or "(ninguna)"

    async def _scan(batch_items) -> list[EntityCandidate]:
        user_text = _build_items_text(
            batch_items, project_name, project_description,
            goals=goals, feedback=feedback,
        )
        user_text += (
            f"\nENTIDADES YA IDENTIFICADAS: {already_listed}\n"
            "Revisa SOLO los requerimientos anteriores y determina si generan "
            "entidades NUEVAS (no listadas arriba).\n"
        )
        msgs = [("system", _GAP_PASS_PROMPT), ("human", user_text)]
        try:
            result = await invoke_structured_resilient(
                lambda **kw: structured_llm(EntityDiscoverySchema, **kw),
                msgs,
                context_label=f"mer_gap_pass ({len(batch_items)} items)",
            )
            return list(result.entities)
        except Exception:
            logger.exception(
                "_gap_pass: all retries exhausted for %d items",
                len(batch_items),
            )
            return []

    batches = list(_chunk(uncovered_items, _MER_BATCH_SIZE))
    total = len(batches)
    if total <= 1:
        if on_progress is not None:
            await on_progress("re-escaneo de requerimientos no cubiertos (1/1 lote)")
        return _dedupe_candidates(await _scan(uncovered_items))
    sem = asyncio.Semaphore(concurrency)
    done = 0

    async def _guarded(batch):
        nonlocal done
        async with sem:
            result = await _scan(batch)
            done += 1
            if on_progress is not None:
                await on_progress(
                    f"re-escaneo de no cubiertos ({done}/{total} lotes)"
                )
            return result

    results = await asyncio.gather(
        *[_guarded(b) for b in batches], return_exceptions=True
    )
    extra: list[EntityCandidate] = []
    for i, r in enumerate(results):
        if isinstance(r, Exception):
            logger.warning(
                "_gap_pass: batch %d/%d failed: %s", i + 1, total, r
            )
            continue
        extra.extend(r)
    return _dedupe_candidates(extra)


# ---------------------------------------------------------------------------
# Pass 3: attributes + relationships (entity-constrained)
# ---------------------------------------------------------------------------


async def _detail_entities_relationships(
    items,
    candidates: list[EntityCandidate],
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
    feedback: str = "",
    concurrency: int = DEFAULT_CONCURRENCY,
    on_progress=None,
) -> tuple[list[MerEntitySchema], list[MerRelationshipSchema]]:
    """Pass 3: attributes + relationships, batched over the candidate list.

    The batch size is ``_MER_DETAIL_BATCH_SIZE`` (small on purpose: the
    structured OUTPUT is what overflows the completion budget, not the
    input). Each batch receives only the requirements traced to its own
    entities (lookup by ``traced_req_codes``) plus the FULL entity name list,
    so the model can emit cross-batch relationships that still validate in
    Pass 4. With no candidates the pass short-circuits without an LLM call.
    The base entity list is the candidate list — an entity whose batch failed
    comes back without attributes (graceful degradation) instead of
    disappearing from the model.

    ``on_progress`` (optional) is awaited with a short human message after
    each batch so callers (the agentic tool) can stream live progress.
    """
    if not candidates:
        return ([], [])

    entity_list_str = "\n".join(f"- {c.name}" for c in candidates)
    items_by_code = {it.code: it for it in items}

    def _entity_key(name: str) -> str:
        return name.lower().strip()

    async def _detail_batch(batch: list[EntityCandidate]):
        batch_reqs = [
            items_by_code[code]
            for c in batch
            for code in c.traced_req_codes
            if code in items_by_code
        ]
        # Only THIS batch's entities go into the detail instruction — the
        # full list stays in the context block above as the naming universe.
        batch_names = ", ".join(c.name for c in batch)
        user_text = _build_items_text(
            batch_reqs, project_name, project_description,
            goals=goals, feedback=feedback,
        )
        user_text += (
            f"\nENTIDADES DEL DOMINIO (usa SOLO estos nombres):\n"
            f"{entity_list_str}\n\n"
            f"DETALLA SOLO ESTAS ENTIDADES: {batch_names}\n"
        )
        msgs = [("system", _DETAIL_PROMPT), ("human", user_text)]
        try:
            return await invoke_structured_resilient(
                lambda **kw: structured_llm(MerDetailSchema, **kw),
                msgs,
                context_label=f"mer_detail ({len(batch)} entities)",
            )
        except Exception:
            logger.exception(
                "_detail_entities_relationships: batch of %d entities failed",
                len(batch),
            )
            return None

    batches = list(_chunk(candidates, _MER_DETAIL_BATCH_SIZE))
    total_batches = len(batches)
    sem = asyncio.Semaphore(concurrency)
    done = 0
    failed = 0

    async def _guarded(batch):
        nonlocal done, failed
        async with sem:
            result = await _detail_batch(batch)
            done += 1
            if result is None:
                failed += 1
            if on_progress is not None:
                detail = (
                    f"lote {done}/{total_batches} completado"
                    if result is not None
                    else f"lote {done}/{total_batches} falló, se continúa "
                    "con el resto"
                )
                await on_progress(
                    f"atributos y relaciones ({done}/{total_batches} lotes): "
                    f"{detail}"
                )
            return result

    results = await asyncio.gather(
        *[_guarded(b) for b in batches], return_exceptions=True
    )

    attributes_by_key: dict[str, list[MerAttribute]] = {}
    relationships: list[MerRelationshipSchema] = []
    for i, r in enumerate(results):
        if isinstance(r, Exception):
            logger.warning(
                "_detail_entities_relationships: batch %d/%d failed: %s",
                i + 1, total_batches, r,
            )
            failed += 1
            continue
        if r is None:
            continue
        for det in r.entities:
            attributes_by_key[_entity_key(det.name)] = det.attributes
        relationships.extend(r.relationships)

    logger.info(
        "mer_detail: %d/%d lotes ok (%d fallidos) sobre %d entidades",
        total_batches - failed, total_batches, failed, len(candidates),
    )

    entities_full: list[MerEntitySchema] = []
    for c in candidates:
        entities_full.append(
            MerEntitySchema(
                name=c.name,
                description=c.description,
                attributes=attributes_by_key.get(_entity_key(c.name), []),
                aggregate_root=c.aggregate_root,
                bounded_context=c.bounded_context,
                traced_req_codes=c.traced_req_codes,
            )
        )
    return (entities_full, relationships)


# ---------------------------------------------------------------------------
# Pass 4: deterministic validation
# ---------------------------------------------------------------------------


def _reconcile_relationship_endpoints(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
    *,
    max_report: int = 50,
) -> tuple[list[MerRelationshipSchema], dict[str, Any], list[str]]:
    """Pass 3d: re-apunta extremos de relaciones a nombres canonicos.

    La pasada de detalle acumula relaciones de lotes independientes y el LLM
    puede emitir variantes del nombre canonico ("ConfiguracionConexion" vs
    "Configuracion de Conexion"); la consolidacion 3b solo re-apunta nombres
    exactos. Una arista con extremo inexistente renderizaria un nodo fantasma
    en el erDiagram sin contraparte en el diccionario de datos, asi que cada
    extremo se resuelve con ``resolve_entity_reference`` y las aristas sin
    resolucion (o ambiguas) se descartan con warning explicito.
    """
    names = [e.name for e in entities]
    kept: list[MerRelationshipSchema] = []
    reconciled: list[dict[str, str]] = []
    warnings: list[str] = []
    seen_edges: set[tuple[str, str, str]] = set()
    reconciled_count = 0
    dropped_count = 0
    deduped_count = 0
    for rel in relationships:
        new_from = resolve_entity_reference(rel.from_entity, names)
        new_to = resolve_entity_reference(rel.to_entity, names)
        if new_from is None or new_to is None:
            dropped_count += 1
            for side, resolved in (
                ("from_entity", new_from),
                ("to_entity", new_to),
            ):
                if resolved is not None:
                    continue
                bad = rel.from_entity if side == "from_entity" else rel.to_entity
                warnings.append(
                    f"Relacion descartada por extremo sin entidad "
                    f"({side}): {bad}"
                )
            continue
        for side, old, new in (
            ("from", rel.from_entity, new_from),
            ("to", rel.to_entity, new_to),
        ):
            if old != new:
                reconciled_count += 1
                if len(reconciled) < max_report:
                    reconciled.append({"side": side, "was": old, "now": new})
        rel.from_entity = new_from
        rel.to_entity = new_to
        edge = (
            new_from.lower(),
            new_to.lower(),
            (rel.label or "").strip().lower(),
        )
        if edge in seen_edges:
            # Dos variantes pueden converger a la misma arista tras el
            # re-apuntado; sin dedupe el render duplicaria la linea.
            deduped_count += 1
            continue
        seen_edges.add(edge)
        kept.append(rel)
    stats = {
        "reconciled": reconciled,
        "reconciled_count": reconciled_count,
        "dropped_count": dropped_count,
        "deduped_count": deduped_count,
    }
    return kept, stats, warnings


def _validate_mer(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
) -> list[str]:
    """Pass 4: deterministic validation checks (no LLM).

    Returns a list of warning strings. Each warning describes one issue found.
    An empty list means the model passed all deterministic checks.
    """
    warnings: list[str] = []
    entity_names_lower = {e.name.lower() for e in entities}

    # Check: no duplicate entity names (case-insensitive).
    seen: set[str] = set()
    for e in entities:
        lower = e.name.lower()
        if lower in seen:
            warnings.append(
                f"Entidad duplicada (ignorando mayusculas): {e.name}"
            )
        seen.add(lower)

    # Check: every entity has at least one PK.
    for e in entities:
        if not any(a.is_key for a in e.attributes):
            warnings.append(
                f"Entidad sin PK (is_key=True): {e.name}"
            )

    # Check: relationships reference existing entities.
    for rel in relationships:
        if rel.from_entity.lower() not in entity_names_lower:
            warnings.append(
                f"Relacion referencia entidad inexistente (from_entity): "
                f"{rel.from_entity}"
            )
        if rel.to_entity.lower() not in entity_names_lower:
            warnings.append(
                f"Relacion referencia entidad inexistente (to_entity): "
                f"{rel.to_entity}"
            )

    # Check: valid cardinality values.
    valid_cardinalities = {"1:1", "1:N", "N:M"}
    for rel in relationships:
        if rel.cardinality not in valid_cardinalities:
            warnings.append(
                f"Cardinalidad invalida '{rel.cardinality}' en relacion "
                f"{rel.from_entity} -> {rel.to_entity}"
            )

    return warnings


# ---------------------------------------------------------------------------
# Pass 5: LLM critique
# ---------------------------------------------------------------------------


async def _critique_mer(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
    items,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
) -> list[MerCritiqueFinding]:
    """Pass 5: LLM critique covering documented failure modes."""
    # Build summaries.
    entity_lines = []
    for e in entities:
        attrs = ", ".join(a.name for a in e.attributes[:5]) or "(sin atributos)"
        entity_lines.append(f"- {e.name} ({attrs})")
    entity_summary = "\n".join(entity_lines) or "(ninguna)"

    rel_lines = []
    for r in relationships:
        rel_lines.append(
            f"- {r.from_entity} {r.cardinality} {r.to_entity}: {r.label}"
        )
    rel_summary = "\n".join(rel_lines) or "(ninguna)"

    req_lines = [f"- {it.code}: {it.statement[:100]}" for it in items[:30]]
    req_summary = "\n".join(req_lines)
    if len(items) > 30:
        req_summary += f"\n... ({len(items) - 30} mas)"

    header_lines = []
    if project_name:
        header_lines.append(f"PROYECTO: {project_name}")
    if project_description:
        header_lines.append(f"DESCRIPCION: {project_description}")
    header = "\n".join(header_lines)

    goals_block = (
        _format_goals(goals, section_title="OBJETIVOS DEL SISTEMA")
        if goals
        else ""
    )

    user_text = (
        f"{header}\n\n"
        f"{goals_block}"
        f"REQUERIMIENTOS ORIGINALES:\n{req_summary}\n\n"
        f"ENTIDADES DEL MER GENERADO:\n{entity_summary}\n\n"
        f"RELACIONES DEL MER GENERADO:\n{rel_summary}\n"
    )
    msgs = [("system", _CRITIQUE_PROMPT), ("human", user_text)]
    llm = structured_llm(MerCritiqueSchema)
    try:
        result = await _invoke_with_retry(
            llm, msgs, context_label="mer_critique"
        )
        return list(result.findings)
    except Exception:
        logger.exception("_critique_mer: all retries exhausted")
        return []


# ---------------------------------------------------------------------------
# Pass 6: narrative description (for analysis view)
# ---------------------------------------------------------------------------


async def _describe_mer(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
    items,
    project_name: str,
    project_description: str,
    goals: list[Any] | None = None,
) -> str:
    """Pass 6: generate a short narrative description of the MER model.

    Returns a prose description (2-3 sentences) or "" on failure.
    The description is shown in the analysis view below the erDiagram.
    """
    entity_lines = []
    for e in entities:
        attrs = ", ".join(a.name for a in e.attributes[:5]) or "(sin atributos)"
        entity_lines.append(f"- {e.name} ({attrs})")
    entity_summary = "\n".join(entity_lines) or "(ninguna)"

    rel_lines = []
    for r in relationships:
        rel_lines.append(
            f"- {r.from_entity} {r.cardinality} {r.to_entity}: {r.label}"
        )
    rel_summary = "\n".join(rel_lines) or "(ninguna)"

    header_lines = []
    if project_name:
        header_lines.append(f"PROYECTO: {project_name}")
    if project_description:
        header_lines.append(f"DESCRIPCION: {project_description}")
    header = "\n".join(header_lines)

    goals_block = (
        _format_goals(goals, section_title="OBJETIVOS DEL SISTEMA")
        if goals
        else ""
    )

    user_text = (
        f"{header}\n\n"
        f"{goals_block}"
        f"ENTIDADES DEL MER:\n{entity_summary}\n\n"
        f"RELACIONES DEL MER:\n{rel_summary}\n"
    )
    msgs = [("system", _MER_DESCRIPTION_PROMPT), ("human", user_text)]
    llm = structured_llm(MerDescriptionSchema)
    try:
        result = await _invoke_with_retry(
            llm, msgs, context_label="mer_describe"
        )
        return result.description
    except Exception:
        logger.exception("_describe_mer: all retries exhausted")
        return ""


# ---------------------------------------------------------------------------
# Public function
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Pass 3b: consolidation (anti over-fragmentation)
# ---------------------------------------------------------------------------

_MER_CONSOLIDATION_PROMPT = (
    "Eres un modelador de datos. Recibes grupos de entidades candidatas a "
    "fusion que un heuristico detecto como posibles DUPLICADOS, SINONIMOS o "
    "FRAGMENTOS de una misma entidad (ej. 'Cliente' + 'Customer' + "
    "'ClientePrincipal', o 'PedidoItem' + 'PedidoLinea'). Decide que "
    "fusiones son correctas.\n\n"
    "Reglas:\n"
    "- SOLO fusiona entidades que claramente modelan el mismo concepto del "
    "dominio. Ante duda, NO fusiones (es preferible dejar una entidad de mas).\n"
    "- keep debe ser el nombre mas claro y canonicamente correcto del grupo.\n"
    "- absorb y keep usan nombres EXACTOS de la lista recibida.\n"
    "- No inventes entidades ni nombres nuevos.\n"
    "- Si un grupo NO debe fusionarse, simplemente omite ese grupo.\n"
    "Devuelve SOLO el objeto estructurado."
)

_SINGULAR_SUFFIXES = ("s", "es", "as")


def _normalize_entity_name(name: str) -> str:
    """Lowercase + strip accents/spaces + naive singular for grouping."""
    import unicodedata

    lowered = unicodedata.normalize(
        "NFKD", name.strip().lower()
    )
    lowered = "".join(
        c for c in lowered if not unicodedata.combining(c)
    )
    lowered = re.sub(r"[^a-z0-9]", "", lowered)
    for suf in _SINGULAR_SUFFIXES:
        if lowered.endswith(suf) and len(lowered) > len(suf) + 2:
            return lowered[: -len(suf)]
    return lowered


_SPANISH_STOPWORDS = frozenset(
    {"a", "de", "del", "el", "en", "la", "las", "los", "y"}
)


def _compact_entity_name(name: str) -> str:
    """Nombre normalizado sin stopwords españoles (match de último recurso)."""
    import unicodedata

    lowered = unicodedata.normalize("NFKD", name.strip().lower())
    lowered = "".join(c for c in lowered if not unicodedata.combining(c))
    tokens = re.split(r"[^a-z0-9]+", lowered)
    return "".join(t for t in tokens if t and t not in _SPANISH_STOPWORDS)


def resolve_entity_reference(
    reference: str, names: list[str]
) -> str | None:
    """Resuelve un extremo de relacion (posible variante) a un nombre de entidad.

    Niveles de match, del mas estricto al mas laxo; un nivel con 2+
    candidatos se rechaza como ambiguo (nunca adivinar):
    1. Exacto ignorando mayusculas.
    2. ``_normalize_entity_name`` (acentos/separadores/plural).
    3. Compaccion sin stopwords (``ConfiguracionConexion`` ->
       ``Configuracion de Conexion``).
    """
    ref = (reference or "").strip()
    if not ref:
        return None
    by_lower = {n.lower(): n for n in names}
    exact = by_lower.get(ref.lower())
    if exact is not None:
        return exact
    ref_norm = _normalize_entity_name(ref)
    normalized = [n for n in names if _normalize_entity_name(n) == ref_norm]
    if len(normalized) == 1:
        return normalized[0]
    ref_compact = _compact_entity_name(ref)
    compact = [n for n in names if _compact_entity_name(n) == ref_compact]
    if len(compact) == 1:
        return compact[0]
    return None


def _candidate_consolidation_groups(
    entities: list[MerEntitySchema],
) -> list[list[str]]:
    """Detect candidate duplicate/synonym groups deterministically (0 LLM).

    Tres senales, ninguna decisiva por si sola pero suficientes para
    acotar el trabajo del LLM a los pares plausibles:
    - nombres equivalentes tras normalizar (singular, acentos, separadores);
    - un nombre es prefijo del otro (Fragmento de una misma entidad:
      OrderItem/OrderLine vs Order se maneja por prefix group);
    - solapamiento fuerte de traced_req_codes (>= 60% del menor).
    Devuelve grupos de >= 2 nombres.
    """
    # Union-find ligero sobre pares candidatos.
    parent: dict[str, str] = {e.name: e.name for e in entities}

    def find(x: str) -> str:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a: str, b: str) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    by_norm: dict[str, str] = {}
    for e in entities:
        norm = _normalize_entity_name(e.name)
        first = by_norm.setdefault(norm, e.name)
        if first != e.name:
            union(first, e.name)

    codes_by_name: dict[str, set[str]] = {
        e.name: set(e.traced_req_codes or []) for e in entities
    }
    names = [e.name for e in entities]
    for i, a in enumerate(names):
        for b in names[i + 1 :]:
            codes_a = codes_by_name[a]
            codes_b = codes_by_name[b]
            if not codes_a or not codes_b:
                continue
            overlap = len(codes_a & codes_b)
            smaller = min(len(codes_a), len(codes_b))
            if overlap and overlap / smaller >= 0.6:
                union(a, b)

    groups: dict[str, set[str]] = {}
    for e in entities:
        groups.setdefault(find(e.name), set()).add(e.name)
    return [
        sorted(g) for g in groups.values() if len(g) >= 2
    ]


async def _consolidate_entities(
    entities: list[MerEntitySchema],
    relationships: list[MerRelationshipSchema],
    *,
    project_name: str = "",
    concurrency: int = DEFAULT_CONCURRENCY,
    on_progress=None,
) -> tuple[
    list[MerEntitySchema],
    list[MerRelationshipSchema],
    list[dict],
]:
    """Pass 3b: fusion de entidades duplicadas/sinonimas (afinamiento).

    Deteccion determinista de grupos candidatos (0 LLM) + consolidacion LLM
    batcheada que SOLO decide que grupos fusionar (output angosto). El merge
    en si es determinista: keep absorbe atributos (dedup por nombre) y
    trazas; las relaciones que apuntaban a absorbidas se re-apuntan a keep
    (dedup de pares equivalentes). Un lote que falla degrada a "sin merges
    de ese lote"; si TODOS fallan devuelve la entrada intacta.
    """
    before = len(entities)
    groups = _candidate_consolidation_groups(entities)
    if not groups:
        return entities, relationships, []

    # Resolver unions transitivas: cada grupo es un set de nombres; el LLM
    # decide que fusiones (keep/absorb) hacer dentro de cada grupo.
    name_set = {e.name for e in entities}
    batches = list(_chunk(groups, _MER_CONSOLIDATION_BATCH_SIZE))
    total_batches = len(batches)
    state: dict[str, int] = {"done": 0, "failed": 0}
    merges: list[dict] = []

    async def _ask(batch: list[list[str]]):
        lines = []
        for group in batch:
            members = ", ".join(group)
            lines.append(f"- [{members}]")
        msgs = [
            ("system", _MER_CONSOLIDATION_PROMPT),
            (
                "human",
                "GRUPOS CANDIDATOS (nombre [contexto]):\n"
                + "\n".join(lines)
                + "\n",
            ),
        ]
        try:
            return await invoke_structured_resilient(
                lambda **kw: structured_llm(MerConsolidationSchema, **kw),
                msgs,
                context_label=f"mer_consolidate ({len(batch)} grupos)",
            )
        except Exception:
            logger.exception("_consolidate_entities: lote fallo")
            return None

    sem = asyncio.Semaphore(concurrency)

    async def _guarded(batch):
        async with sem:
            result = await _ask(batch)
            state["done"] += 1
            if result is None:
                state["failed"] += 1
            if on_progress is not None:
                detail = (
                    f"lote {state['done']}/{total_batches} completado"
                    if result is not None
                    else f"lote {state['done']}/{total_batches} fallo, se "
                    "continua con el resto"
                )
                await on_progress(
                    f"afinando MER ({state['done']}/{total_batches} lotes): {detail}"
                )
            return result

    results = await asyncio.gather(
        *[_guarded(b) for b in batches], return_exceptions=True
    )
    ok_results = [
        r for r in results if isinstance(r, MerConsolidationSchema)
    ]
    failed = total_batches - len(ok_results)
    logger.info(
        "mer_consolidate: %d/%d lotes ok (%d fallidos) sobre %d grupos",
        len(ok_results), total_batches, failed, len(groups),
    )
    if not ok_results:
        return entities, relationships, []

    for schema in ok_results:
        for m in schema.merges:
            if m.keep not in name_set:
                continue
            absorb = [a for a in m.absorb if a in name_set and a != m.keep]
            if not absorb:
                continue
            merges.append({
                "keep": m.keep,
                "absorb": absorb,
                "reason": m.reason,
            })

    # Merge determinista.
    absorbed_names: set[str] = set()
    for m in merges:
        absorbed_names.update(m["absorb"])
    if not absorbed_names:
        return entities, relationships, []

    by_name = {e.name: e for e in entities}
    keepers = [e for e in entities if e.name not in absorbed_names]
    for m in merges:
        keep = by_name.get(m["keep"])
        if keep is None:
            continue
        keep_attrs: set[str] = {a.name.lower() for a in keep.attributes}
        for absorbed_name in m["absorb"]:
            absorbed = by_name.get(absorbed_name)
            if absorbed is None or absorbed.name in (
                absorbed_names - {absorbed_name}
            ) and absorbed_name != m["keep"] and absorbed is keep:
                continue
            if absorbed is None or absorbed is keep:
                continue
            for attr in absorbed.attributes:
                if attr.name.lower() not in keep_attrs:
                    keep.attributes.append(attr)
                    keep_attrs.add(attr.name.lower())
            for code in absorbed.traced_req_codes:
                if code not in keep.traced_req_codes:
                    keep.traced_req_codes.append(code)
            if not keep.description and absorbed.description:
                keep.description = absorbed.description
            if not keep.bounded_context and absorbed.bounded_context:
                keep.bounded_context = absorbed.bounded_context
            if absorbed.aggregate_root:
                keep.aggregate_root = True

    # Re-apuntar relaciones de absorbidas hacia keep y deduplicar.
    redirect = {
        absorbed: m["keep"]
        for m in merges
        for absorbed in m["absorb"]
    }
    seen_rels: set[tuple] = set()
    new_rels: list[MerRelationshipSchema] = []
    for rel in relationships:
        rel.from_entity = redirect.get(rel.from_entity, rel.from_entity)
        rel.to_entity = redirect.get(rel.to_entity, rel.to_entity)
        if rel.from_entity == rel.to_entity:
            continue  # self-loop creado por el merge
        if rel.from_entity in absorbed_names or rel.to_entity in absorbed_names:
            continue
        key = (rel.from_entity.lower(), rel.to_entity.lower(), rel.cardinality)
        if key in seen_rels:
            continue
        seen_rels.add(key)
        new_rels.append(rel)

    return keepers, new_rels, merges


# ---------------------------------------------------------------------------
# Pass 3c: higiene de contextos acotados
# ---------------------------------------------------------------------------


_CONTEXT_STOPWORDS = re.compile(
    r"\b(de|del|la|el|los|las|y|e|en|para)\b", re.IGNORECASE
)


def normalize_context_key(bc: str | None) -> str:
    """Clave canonica de una etiqueta de contexto para agrupar variantes.

    Quita acentos, separa camelCase («GestionTerreno» -> «Gestion Terreno»),
    descarta partículas («de», «del», «y», …) y reduce a minusculas
    alfanumericas. «Gestión de Terreno», «Gestion de Terreno» y
    «GestionTerreno» producen la misma clave; «N:M» y otros dominios
    distintos conservan claves separadas.
    """
    if not bc:
        return ""
    decomposed = unicodedata.normalize("NFKD", bc)
    without_accents = "".join(
        c for c in decomposed if not unicodedata.combining(c)
    )
    camel_spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", without_accents)
    without_stopwords = _CONTEXT_STOPWORDS.sub(" ", camel_spaced)
    return re.sub(r"[^a-z0-9]", "", without_stopwords.lower())


def _context_label_counts(entities: list[MerEntitySchema]) -> dict[str, int]:
    """Conteo de entidades por etiqueta de contexto (sin vacias)."""
    counts: dict[str, int] = {}
    for e in entities:
        bc = (e.bounded_context or "").strip()
        if bc:
            counts[bc] = counts.get(bc, 0) + 1
    return counts


def consolidate_context_labels(
    entities: list[MerEntitySchema],
) -> dict[str, str]:
    """Fusiona variantes ortograficas de ``bounded_context`` (0 LLM).

    Agrupa las etiquetas por clave normalizada y reescribe cada entidad a la
    variante representativa del grupo: la mas frecuente; en empate, la mas
    legible (la que tiene espacios). Devuelve el mapeo clave->canonica. Las
    entidades sin contexto quedan intactas.
    """
    counts = _context_label_counts(entities)
    groups: dict[str, list[str]] = {}
    for e in entities:
        bc = (e.bounded_context or "").strip()
        if not bc:
            continue
        groups.setdefault(normalize_context_key(bc), []).append(bc)

    canonical: dict[str, str] = {}
    for key, variants in groups.items():
        canonical[key] = sorted(
            variants, key=lambda v: (-counts[v], " " not in v, v)
        )[0]

    for e in entities:
        bc = (e.bounded_context or "").strip()
        if not bc:
            # Higiene: un contexto de solo espacios equivale a no tener.
            e.bounded_context = ""
            continue
        e.bounded_context = canonical[normalize_context_key(bc)]
    return canonical


async def consolidate_bounded_contexts(
    entities: list[MerEntitySchema],
    *,
    on_progress=None,
) -> tuple[list[MerEntitySchema], dict]:
    """Pass 3c: consolidacion de contextos acotados fragmentados.

    Paso 1 determinista (0 LLM): fusiona variantes ortograficas. Paso 2
    (LLM, solo si quedan mas etiquetas que ``_MER_CONTEXT_TARGET_MAX``): un
    unico llamado de output angosto decide el mapeo etiqueta->canonica; su
    aplicacion es determinista, resuelve cadenas (A->B, B->C) y solo acepta
    canonicos que ya existen en el modelo. Cualquier fallo degrada al paso
    anterior sin abortar el pipeline.
    """
    raw_labels = {
        (e.bounded_context or "").strip()
        for e in entities
        if (e.bounded_context or "").strip()
    }
    consolidate_context_labels(entities)
    norm_labels = {
        (e.bounded_context or "").strip()
        for e in entities
        if (e.bounded_context or "").strip()
    }
    stats: dict = {
        "raw": len(raw_labels),
        "normalized": len(norm_labels),
        "llm_mapped": False,
        "final": len(norm_labels),
    }
    if len(norm_labels) <= _MER_CONTEXT_TARGET_MAX:
        return entities, stats
    if not _MER_CONTEXT_CONSOLIDATE_ENABLED:
        return entities, stats
    if on_progress is not None:
        await on_progress(
            f"consolidando {len(norm_labels)} contextos acotados del MER…"
        )

    counts = _context_label_counts(entities)
    lines = [
        f"- {label} ({counts[label]} entidades)"
        for label in sorted(norm_labels)
    ]
    msgs = [
        ("system", _MER_CONTEXT_CONSOLIDATION_PROMPT),
        ("human", "ETIQUETAS DE CONTEXTO:\n" + "\n".join(lines) + "\n"),
    ]
    try:
        schema = await invoke_structured_resilient(
            lambda **kw: structured_llm(MerContextConsolidationSchema, **kw),
            msgs,
            context_label=f"mer_contexts ({len(norm_labels)} etiquetas)",
        )
    except Exception:
        logger.exception("consolidate_bounded_contexts: mapeo LLM fallo")
        return entities, stats

    resolved: dict[str, str] = {}
    for m in schema.mappings:
        raw = m.raw.strip()
        canon = m.canonical.strip()
        if raw and canon and raw != canon:
            resolved[raw] = canon

    def _final(label: str) -> str:
        seen: set[str] = set()
        cur = label
        while cur in resolved and cur not in seen:
            seen.add(cur)
            cur = resolved[cur]
        return cur

    applied = 0
    for e in entities:
        bc = (e.bounded_context or "").strip()
        if not bc:
            continue
        target = _final(bc)
        if target in norm_labels and target != bc:
            e.bounded_context = target
            applied += 1

    final = {
        (e.bounded_context or "").strip()
        for e in entities
        if (e.bounded_context or "").strip()
    }
    stats.update(
        {
            "llm_mapped": applied > 0,
            "mappings_applied": applied,
            "final": len(final),
        }
    )
    return entities, stats


async def generate_mer(
    items,
    *,
    project_name: str = "",
    project_description: str = "",
    concurrency: int = DEFAULT_CONCURRENCY,
    enable_critique: bool = True,
    goals: list[Any] | None = None,
    feedback: str = "",
    on_progress=None,
) -> MerResult:
    """Generate a domain entity model (MER) from functional requirements.

    Multi-pass pipeline:

      Pass 1 — entity discovery (narrow schema).
      Pass 2 — gap pass for uncovered REQ codes.
      Pass 3 — attributes + relationships (entity-constrained).
      Pass 4 — deterministic validation.
      Pass 5 — LLM critique (optional, enabled by default).

    Takes RequirementItem objects (filtered to functional/data/process types)
    and produces a MerResult with entities, relationships, a Mermaid erDiagram
    string rendered deterministically from the structured LLM output, plus
    validation warnings and critique findings in stats.

    Each pass has its own retry loop (transient backoff + parse retries,
    mirroring classification._classify_item). Failed passes degrade
    gracefully — a failed gap pass returns no extra candidates, a failed
    critique returns no findings — instead of aborting the whole pipeline.
    """
    if not items:
        return MerResult(stats={"input": 0})

    # Pass 1: entity discovery (batched).
    candidates = await _discover_entities(
        items, project_name, project_description,
        goals=goals, feedback=feedback, concurrency=concurrency,
        on_progress=on_progress,
    )

    # Pass 2: gap pass for uncovered requirements (batched).
    gap_candidates = await _gap_pass(
        items, candidates, project_name, project_description,
        goals=goals, feedback=feedback, concurrency=concurrency,
        on_progress=on_progress,
    )
    all_candidates = _dedupe_candidates(candidates + gap_candidates)

    # Pass 3: attributes + relationships (entity-constrained, batched).
    entities_full, relationships = await _detail_entities_relationships(
        items, all_candidates, project_name, project_description,
        goals=goals, feedback=feedback, concurrency=concurrency,
        on_progress=on_progress,
    )

    # Snapshot pre-consolidacion para el reporte (before/after).
    stats_before = len(entities_full)

    # Normalize cardinalities to canonical forms before validation/rendering.
    for rel in relationships:
        rel.cardinality = _normalize_cardinality(rel.cardinality)

    # Pass 3b: consolidation (anti over-fragmentation, env kill-switch).
    consolidation_merges: list[dict] = []
    if _MER_CONSOLIDATE_ENABLED and len(entities_full) > _MER_BATCH_SIZE:
        entities_full, relationships, consolidation_merges = (
            await _consolidate_entities(
                entities_full,
                relationships,
                project_name=project_name,
                concurrency=concurrency,
                on_progress=on_progress,
            )
        )

    # Pass 3c: higiene de contextos acotados (normaliza variantes ortograficas
    # y, si quedan demasiadas etiquetas, las consolida con un mapeo LLM).
    entities_full, context_stats = await consolidate_bounded_contexts(
        entities_full, on_progress=on_progress,
    )

    # Pass 3d: re-apunta extremos de relaciones a nombres canonicos de
    # entidad (evita nodos fantasma en el erDiagram).
    relationships, reconcile_stats, reconcile_warnings = (
        _reconcile_relationship_endpoints(entities_full, relationships)
    )

    # Pass 4: deterministic validation.
    warnings = reconcile_warnings + _validate_mer(entities_full, relationships)

    # Pass 5: LLM critique (optional).
    critique_findings: list[MerCritiqueFinding] = []
    if enable_critique:
        critique_findings = await _critique_mer(
            entities_full, relationships, items, project_name,
            project_description, goals=goals,
        )

    # Pass 6: narrative description (lightweight, always runs).
    description = await _describe_mer(
        entities_full, relationships, items, project_name,
        project_description, goals=goals,
    )

    # Render Mermaid erDiagram deterministically.
    mermaid = _render_mermaid(entities_full, relationships)

    # Compute coverage stats.
    input_codes = {it.code for it in items}
    covered_codes = {c for e in entities_full for c in e.traced_req_codes}
    uncovered = input_codes - covered_codes

    stats = {
        "input": len(items),
        "entities": len(entities_full),
        "relationships": len(relationships),
        "aggregate_roots": sum(1 for e in entities_full if e.aggregate_root),
        "bounded_contexts": len(
            {e.bounded_context for e in entities_full if e.bounded_context}
        ),
        "contexts": context_stats,
        "req_coverage": f"{len(covered_codes)}/{len(input_codes)}",
        "uncovered_codes": sorted(uncovered),
        "gap_pass_found": len(gap_candidates),
        "consolidation": {
            "before": stats_before,
            "after": len(entities_full),
            "merges": consolidation_merges,
        },
        "validation_warnings": warnings,
        "reconciliation": reconcile_stats,
        "critique_findings": [f.model_dump() for f in critique_findings],
        "critique_blockers": sum(
            1 for f in critique_findings if f.severity == "blocker"
        ),
        "data_dictionary": render_data_dictionary(
            entities_full, relationships
        ),
    }
    logger.info(
        "generate_mer: %d items -> %d entities, %d relationships "
        "(gap +%d, %d warnings, %d critique findings)",
        stats["input"],
        stats["entities"],
        stats["relationships"],
        stats["gap_pass_found"],
        len(warnings),
        len(critique_findings),
    )
    return MerResult(
        entities=entities_full,
        relationships=relationships,
        mermaid=mermaid,
        description=description,
        stats=stats,
    )
