"""Model package. Importing this module registers all tables on Base.metadata."""
from backend.models.base import Base
from backend.models.chat_message import ChatMessage
from backend.models.chat_session import ChatSession
from backend.models.project import Project
from backend.models.requirement import (
    ChangedBy,
    GroupDecision,
    GroupingGroup,
    GroupingPlan,
    PlanStatus,
    Priority,
    RelationKind,
    RelationStatus,
    ReqStatus,
    ReqType,
    RequirementItem,
    RequirementRelation,
    RequirementRevision,
)
from backend.models.srs import (
    FindingDimension,
    FindingScope,
    FindingSeverity,
    FindingStatus,
    Goal,
    GoalKind,
    GoalLink,
    GoalStatus,
    LinkRelation,
    LinkStatus,
    RequirementFinding,
    SrsDocument,
    SrsStatus,
)
from backend.models.user import User

__all__ = [
    "Base",
    "User",
    "Project",
    "ChatSession",
    "ChatMessage",
    "RequirementItem",
    "RequirementRelation",
    "RequirementRevision",
    "GroupingPlan",
    "GroupingGroup",
    "ReqType",
    "Priority",
    "ReqStatus",
    "RelationKind",
    "RelationStatus",
    "ChangedBy",
    "PlanStatus",
    "GroupDecision",
    "RequirementFinding",
    "Goal",
    "GoalLink",
    "SrsDocument",
    "FindingScope",
    "FindingDimension",
    "FindingSeverity",
    "FindingStatus",
    "GoalKind",
    "GoalStatus",
    "LinkRelation",
    "LinkStatus",
    "SrsStatus",
]
